// City database: @vvo/tzdb | cc = ISO code for lipis/flag-icons
const CITIES=[
  {name:"Midway",country:"United States Minor Outlying Islands",cc:"um",tz:"Pacific/Midway",region:"oceania",pop:0},
  {name:"Pago Pago",country:"American Samoa",cc:"as",tz:"Pacific/Pago_Pago",region:"oceania",pop:0},
  {name:"Alofi",country:"Niue",cc:"nu",tz:"Pacific/Niue",region:"oceania",pop:0},
  {name:"Avarua",country:"Cook Islands",cc:"ck",tz:"Pacific/Rarotonga",region:"oceania",pop:0},
  {name:"Adak",country:"United States",cc:"us",tz:"America/Adak",region:"americas",pop:0},
  {name:"Honolulu",country:"United States",cc:"us",tz:"Pacific/Honolulu",region:"americas",pop:1},
  {name:"East Honolulu",country:"United States",cc:"us",tz:"Pacific/Honolulu",region:"americas",pop:0},
  {name:"Pearl City",country:"United States",cc:"us",tz:"Pacific/Honolulu",region:"americas",pop:0},
  {name:"Makakilo / Kapolei / Honokai Hale",country:"United States",cc:"us",tz:"Pacific/Honolulu",region:"americas",pop:0},
  {name:"Faaa",country:"French Polynesia",cc:"pf",tz:"Pacific/Tahiti",region:"oceania",pop:0},
  {name:"Papeete",country:"French Polynesia",cc:"pf",tz:"Pacific/Tahiti",region:"oceania",pop:0},
  {name:"Punaauia",country:"French Polynesia",cc:"pf",tz:"Pacific/Tahiti",region:"oceania",pop:0},
  {name:"Marquesas",country:"French Polynesia",cc:"pf",tz:"Pacific/Marquesas",region:"oceania",pop:0},
  {name:"Anchorage",country:"United States",cc:"us",tz:"America/Anchorage",region:"americas",pop:1},
  {name:"Fairbanks",country:"United States",cc:"us",tz:"America/Anchorage",region:"americas",pop:0},
  {name:"Juneau",country:"United States",cc:"us",tz:"America/Anchorage",region:"americas",pop:0},
  {name:"Eagle River",country:"United States",cc:"us",tz:"America/Anchorage",region:"americas",pop:0},
  {name:"Gambier",country:"French Polynesia",cc:"pf",tz:"Pacific/Gambier",region:"oceania",pop:0},
  {name:"Los Angeles",country:"United States",cc:"us",tz:"America/Los_Angeles",region:"americas",pop:1},
  {name:"San Diego",country:"United States",cc:"us",tz:"America/Los_Angeles",region:"americas",pop:1},
  {name:"San Jose",country:"United States",cc:"us",tz:"America/Los_Angeles",region:"americas",pop:0},
  {name:"San Francisco",country:"United States",cc:"us",tz:"America/Los_Angeles",region:"americas",pop:0},
  {name:"Tijuana",country:"Mexico",cc:"mx",tz:"America/Tijuana",region:"americas",pop:0},
  {name:"Mexicali",country:"Mexico",cc:"mx",tz:"America/Tijuana",region:"americas",pop:0},
  {name:"Ensenada",country:"Mexico",cc:"mx",tz:"America/Tijuana",region:"americas",pop:0},
  {name:"Rosarito",country:"Mexico",cc:"mx",tz:"America/Tijuana",region:"americas",pop:0},
  {name:"Vancouver",country:"Canada",cc:"ca",tz:"America/Vancouver",region:"americas",pop:1},
  {name:"Surrey",country:"Canada",cc:"ca",tz:"America/Vancouver",region:"americas",pop:0},
  {name:"Victoria",country:"Canada",cc:"ca",tz:"America/Vancouver",region:"americas",pop:0},
  {name:"Burnaby",country:"Canada",cc:"ca",tz:"America/Vancouver",region:"americas",pop:0},
  {name:"Adamstown",country:"Pitcairn",cc:"pn",tz:"Pacific/Pitcairn",region:"oceania",pop:0},
  {name:"Hermosillo",country:"Mexico",cc:"mx",tz:"America/Hermosillo",region:"americas",pop:0},
  {name:"Culiac\u00e1n",country:"Mexico",cc:"mx",tz:"America/Hermosillo",region:"americas",pop:0},
  {name:"Mazatl\u00e1n",country:"Mexico",cc:"mx",tz:"America/Hermosillo",region:"americas",pop:0},
  {name:"Tepic",country:"Mexico",cc:"mx",tz:"America/Hermosillo",region:"americas",pop:0},
  {name:"Calgary",country:"Canada",cc:"ca",tz:"America/Edmonton",region:"americas",pop:1},
  {name:"Edmonton",country:"Canada",cc:"ca",tz:"America/Edmonton",region:"americas",pop:0},
  {name:"Lethbridge",country:"Canada",cc:"ca",tz:"America/Edmonton",region:"americas",pop:0},
  {name:"Red Deer",country:"Canada",cc:"ca",tz:"America/Edmonton",region:"americas",pop:0},
  {name:"Ciudad Ju\u00e1rez",country:"Mexico",cc:"mx",tz:"America/Ciudad_Juarez",region:"americas",pop:0},
  {name:"Denver",country:"United States",cc:"us",tz:"America/Denver",region:"americas",pop:1},
  {name:"El Paso",country:"United States",cc:"us",tz:"America/Denver",region:"americas",pop:0},
  {name:"Albuquerque",country:"United States",cc:"us",tz:"America/Denver",region:"americas",pop:0},
  {name:"Colorado Springs",country:"United States",cc:"us",tz:"America/Denver",region:"americas",pop:0},
  {name:"Phoenix",country:"United States",cc:"us",tz:"America/Phoenix",region:"americas",pop:1},
  {name:"Tucson",country:"United States",cc:"us",tz:"America/Phoenix",region:"americas",pop:0},
  {name:"Mesa",country:"United States",cc:"us",tz:"America/Phoenix",region:"americas",pop:0},
  {name:"Chandler",country:"United States",cc:"us",tz:"America/Phoenix",region:"americas",pop:0},
  {name:"Whitehorse",country:"Canada",cc:"ca",tz:"America/Whitehorse",region:"americas",pop:0},
  {name:"Fort St. John",country:"Canada",cc:"ca",tz:"America/Whitehorse",region:"americas",pop:0},
  {name:"Creston",country:"Canada",cc:"ca",tz:"America/Whitehorse",region:"americas",pop:0},
  {name:"Dawson",country:"Canada",cc:"ca",tz:"America/Whitehorse",region:"americas",pop:0},
  {name:"Belize City",country:"Belize",cc:"bz",tz:"America/Belize",region:"americas",pop:0},
  {name:"San Pedro",country:"Belize",cc:"bz",tz:"America/Belize",region:"americas",pop:0},
  {name:"Orange Walk",country:"Belize",cc:"bz",tz:"America/Belize",region:"americas",pop:0},
  {name:"Belmopan",country:"Belize",cc:"bz",tz:"America/Belize",region:"americas",pop:0},
  {name:"Chicago",country:"United States",cc:"us",tz:"America/Chicago",region:"americas",pop:1},
  {name:"Houston",country:"United States",cc:"us",tz:"America/Chicago",region:"americas",pop:1},
  {name:"San Antonio",country:"United States",cc:"us",tz:"America/Chicago",region:"americas",pop:1},
  {name:"Dallas",country:"United States",cc:"us",tz:"America/Chicago",region:"americas",pop:1},
  {name:"Guatemala City",country:"Guatemala",cc:"gt",tz:"America/Guatemala",region:"americas",pop:1},
  {name:"Villa Nueva",country:"Guatemala",cc:"gt",tz:"America/Guatemala",region:"americas",pop:0},
  {name:"Mixco",country:"Guatemala",cc:"gt",tz:"America/Guatemala",region:"americas",pop:0},
  {name:"Cob\u00e1n",country:"Guatemala",cc:"gt",tz:"America/Guatemala",region:"americas",pop:0},
  {name:"Managua",country:"Nicaragua",cc:"ni",tz:"America/Managua",region:"americas",pop:1},
  {name:"Le\u00f3n",country:"Nicaragua",cc:"ni",tz:"America/Managua",region:"americas",pop:0},
  {name:"Masaya",country:"Nicaragua",cc:"ni",tz:"America/Managua",region:"americas",pop:0},
  {name:"Chinandega",country:"Nicaragua",cc:"ni",tz:"America/Managua",region:"americas",pop:0},
  {name:"Mexico City",country:"Mexico",cc:"mx",tz:"America/Mexico_City",region:"americas",pop:1},
  {name:"Iztapalapa",country:"Mexico",cc:"mx",tz:"America/Mexico_City",region:"americas",pop:0},
  {name:"Puebla",country:"Mexico",cc:"mx",tz:"America/Mexico_City",region:"americas",pop:0},
  {name:"Ecatepec de Morelos",country:"Mexico",cc:"mx",tz:"America/Mexico_City",region:"americas",pop:0},
  {name:"Reynosa",country:"Mexico",cc:"mx",tz:"America/Matamoros",region:"americas",pop:0},
  {name:"Heroica Matamoros",country:"Mexico",cc:"mx",tz:"America/Matamoros",region:"americas",pop:0},
  {name:"Nuevo Laredo",country:"Mexico",cc:"mx",tz:"America/Matamoros",region:"americas",pop:0},
  {name:"Ciudad Acu\u00f1a",country:"Mexico",cc:"mx",tz:"America/Matamoros",region:"americas",pop:0},
  {name:"San Jos\u00e9",country:"Costa Rica",cc:"cr",tz:"America/Costa_Rica",region:"americas",pop:0},
  {name:"Lim\u00f3n",country:"Costa Rica",cc:"cr",tz:"America/Costa_Rica",region:"americas",pop:0},
  {name:"Alajuela",country:"Costa Rica",cc:"cr",tz:"America/Costa_Rica",region:"americas",pop:0},
  {name:"San Salvador",country:"El Salvador",cc:"sv",tz:"America/El_Salvador",region:"americas",pop:1},
  {name:"Soyapango",country:"El Salvador",cc:"sv",tz:"America/El_Salvador",region:"americas",pop:0},
  {name:"San Miguel",country:"El Salvador",cc:"sv",tz:"America/El_Salvador",region:"americas",pop:0},
  {name:"Santa Ana",country:"El Salvador",cc:"sv",tz:"America/El_Salvador",region:"americas",pop:0},
  {name:"Saskatoon",country:"Canada",cc:"ca",tz:"America/Regina",region:"americas",pop:0},
  {name:"Regina",country:"Canada",cc:"ca",tz:"America/Regina",region:"americas",pop:0},
  {name:"Prince Albert",country:"Canada",cc:"ca",tz:"America/Regina",region:"americas",pop:0},
  {name:"Moose Jaw",country:"Canada",cc:"ca",tz:"America/Regina",region:"americas",pop:0},
  {name:"Tegucigalpa",country:"Honduras",cc:"hn",tz:"America/Tegucigalpa",region:"americas",pop:1},
  {name:"San Pedro Sula",country:"Honduras",cc:"hn",tz:"America/Tegucigalpa",region:"americas",pop:0},
  {name:"La Ceiba",country:"Honduras",cc:"hn",tz:"America/Tegucigalpa",region:"americas",pop:0},
  {name:"Choloma",country:"Honduras",cc:"hn",tz:"America/Tegucigalpa",region:"americas",pop:0},
  {name:"Winnipeg",country:"Canada",cc:"ca",tz:"America/Winnipeg",region:"americas",pop:0},
  {name:"Brandon",country:"Canada",cc:"ca",tz:"America/Winnipeg",region:"americas",pop:0},
  {name:"Steinbach",country:"Canada",cc:"ca",tz:"America/Winnipeg",region:"americas",pop:0},
  {name:"Kenora",country:"Canada",cc:"ca",tz:"America/Winnipeg",region:"americas",pop:0},
  {name:"Easter",country:"Chile",cc:"cl",tz:"Pacific/Easter",region:"americas",pop:0},
  {name:"Galapagos",country:"Ecuador",cc:"ec",tz:"Pacific/Galapagos",region:"americas",pop:0},
  {name:"Rio Branco",country:"Brazil",cc:"br",tz:"America/Rio_Branco",region:"americas",pop:0},
  {name:"Cruzeiro do Sul",country:"Brazil",cc:"br",tz:"America/Rio_Branco",region:"americas",pop:0},
  {name:"Tarauac\u00e1",country:"Brazil",cc:"br",tz:"America/Rio_Branco",region:"americas",pop:0},
  {name:"Sena Madureira",country:"Brazil",cc:"br",tz:"America/Rio_Branco",region:"americas",pop:0},
  {name:"Bogot\u00e1",country:"Colombia",cc:"co",tz:"America/Bogota",region:"americas",pop:0},
  {name:"Cali",country:"Colombia",cc:"co",tz:"America/Bogota",region:"americas",pop:0},
  {name:"Medell\u00edn",country:"Colombia",cc:"co",tz:"America/Bogota",region:"americas",pop:0},
  {name:"Barranquilla",country:"Colombia",cc:"co",tz:"America/Bogota",region:"americas",pop:0},
  {name:"Havana",country:"Cuba",cc:"cu",tz:"America/Havana",region:"americas",pop:1},
  {name:"Santiago de Cuba",country:"Cuba",cc:"cu",tz:"America/Havana",region:"americas",pop:0},
  {name:"Camag\u00fcey",country:"Cuba",cc:"cu",tz:"America/Havana",region:"americas",pop:0},
  {name:"Holgu\u00edn",country:"Cuba",cc:"cu",tz:"America/Havana",region:"americas",pop:0},
  {name:"Atikokan",country:"Canada",cc:"ca",tz:"America/Atikokan",region:"americas",pop:0},
  {name:"Canc\u00fan",country:"Mexico",cc:"mx",tz:"America/Cancun",region:"americas",pop:0},
  {name:"Chetumal",country:"Mexico",cc:"mx",tz:"America/Cancun",region:"americas",pop:0},
  {name:"Playa del Carmen",country:"Mexico",cc:"mx",tz:"America/Cancun",region:"americas",pop:0},
  {name:"Cozumel",country:"Mexico",cc:"mx",tz:"America/Cancun",region:"americas",pop:0},
  {name:"George Town",country:"Cayman Islands",cc:"ky",tz:"America/Cayman",region:"americas",pop:0},
  {name:"West Bay",country:"Cayman Islands",cc:"ky",tz:"America/Cayman",region:"americas",pop:0},
  {name:"Kingston",country:"Jamaica",cc:"jm",tz:"America/Jamaica",region:"americas",pop:1},
  {name:"New Kingston",country:"Jamaica",cc:"jm",tz:"America/Jamaica",region:"americas",pop:0},
  {name:"Spanish Town",country:"Jamaica",cc:"jm",tz:"America/Jamaica",region:"americas",pop:0},
  {name:"Portmore",country:"Jamaica",cc:"jm",tz:"America/Jamaica",region:"americas",pop:0},
  {name:"Nassau",country:"Bahamas",cc:"bs",tz:"America/Nassau",region:"americas",pop:1},
  {name:"Lucaya",country:"Bahamas",cc:"bs",tz:"America/Nassau",region:"americas",pop:0},
  {name:"Freeport",country:"Bahamas",cc:"bs",tz:"America/Nassau",region:"americas",pop:0},
  {name:"Killarney",country:"Bahamas",cc:"bs",tz:"America/Nassau",region:"americas",pop:0},
  {name:"New York City",country:"United States",cc:"us",tz:"America/New_York",region:"americas",pop:0},
  {name:"Brooklyn",country:"United States",cc:"us",tz:"America/New_York",region:"americas",pop:0},
  {name:"Queens",country:"United States",cc:"us",tz:"America/New_York",region:"americas",pop:0},
  {name:"Philadelphia",country:"United States",cc:"us",tz:"America/New_York",region:"americas",pop:0},
  {name:"Panam\u00e1",country:"Panama",cc:"pa",tz:"America/Panama",region:"americas",pop:0},
  {name:"San Miguelito",country:"Panama",cc:"pa",tz:"America/Panama",region:"americas",pop:0},
  {name:"Juan D\u00edaz",country:"Panama",cc:"pa",tz:"America/Panama",region:"americas",pop:0},
  {name:"David",country:"Panama",cc:"pa",tz:"America/Panama",region:"americas",pop:0},
  {name:"Port-au-Prince",country:"Haiti",cc:"ht",tz:"America/Port-au-Prince",region:"americas",pop:0},
  {name:"Carrefour",country:"Haiti",cc:"ht",tz:"America/Port-au-Prince",region:"americas",pop:0},
  {name:"Delmas",country:"Haiti",cc:"ht",tz:"America/Port-au-Prince",region:"americas",pop:0},
  {name:"Port-de-Paix",country:"Haiti",cc:"ht",tz:"America/Port-au-Prince",region:"americas",pop:0},
  {name:"Providenciales",country:"Turks and Caicos Islands",cc:"tc",tz:"America/Grand_Turk",region:"americas",pop:0},
  {name:"Cockburn Town",country:"Turks and Caicos Islands",cc:"tc",tz:"America/Grand_Turk",region:"americas",pop:0},
  {name:"Toronto",country:"Canada",cc:"ca",tz:"America/Toronto",region:"americas",pop:1},
  {name:"Montr\u00e9al",country:"Canada",cc:"ca",tz:"America/Toronto",region:"americas",pop:0},
  {name:"Ottawa",country:"Canada",cc:"ca",tz:"America/Toronto",region:"americas",pop:1},
  {name:"Mississauga",country:"Canada",cc:"ca",tz:"America/Toronto",region:"americas",pop:0},
  {name:"Quito",country:"Ecuador",cc:"ec",tz:"America/Guayaquil",region:"americas",pop:0},
  {name:"Guayaquil",country:"Ecuador",cc:"ec",tz:"America/Guayaquil",region:"americas",pop:0},
  {name:"Cuenca",country:"Ecuador",cc:"ec",tz:"America/Guayaquil",region:"americas",pop:0},
  {name:"Santo Domingo de los Colorados",country:"Ecuador",cc:"ec",tz:"America/Guayaquil",region:"americas",pop:0},
  {name:"Lima",country:"Peru",cc:"pe",tz:"America/Lima",region:"americas",pop:1},
  {name:"Callao",country:"Peru",cc:"pe",tz:"America/Lima",region:"americas",pop:0},
  {name:"Arequipa",country:"Peru",cc:"pe",tz:"America/Lima",region:"americas",pop:0},
  {name:"Trujillo",country:"Peru",cc:"pe",tz:"America/Lima",region:"americas",pop:0},
  {name:"Manaus",country:"Brazil",cc:"br",tz:"America/Manaus",region:"americas",pop:0},
  {name:"Campo Grande",country:"Brazil",cc:"br",tz:"America/Manaus",region:"americas",pop:0},
  {name:"Cuiab\u00e1",country:"Brazil",cc:"br",tz:"America/Manaus",region:"americas",pop:0},
  {name:"Porto Velho",country:"Brazil",cc:"br",tz:"America/Manaus",region:"americas",pop:0},
  {name:"Basseterre",country:"Saint Kitts and Nevis",cc:"kn",tz:"America/St_Kitts",region:"americas",pop:0},
  {name:"Blanc-Sablon",country:"Canada",cc:"ca",tz:"America/Blanc-Sablon",region:"americas",pop:0},
  {name:"Brades",country:"Montserrat",cc:"ms",tz:"America/Montserrat",region:"americas",pop:0},
  {name:"Plymouth",country:"Montserrat",cc:"ms",tz:"America/Montserrat",region:"americas",pop:0},
  {name:"Bridgetown",country:"Barbados",cc:"bb",tz:"America/Barbados",region:"americas",pop:0},
  {name:"Chaguanas",country:"Trinidad and Tobago",cc:"tt",tz:"America/Port_of_Spain",region:"americas",pop:0},
  {name:"Mon Repos",country:"Trinidad and Tobago",cc:"tt",tz:"America/Port_of_Spain",region:"americas",pop:0},
  {name:"San Fernando",country:"Trinidad and Tobago",cc:"tt",tz:"America/Port_of_Spain",region:"americas",pop:0},
  {name:"Port of Spain",country:"Trinidad and Tobago",cc:"tt",tz:"America/Port_of_Spain",region:"americas",pop:0},
  {name:"Fort-de-France",country:"Martinique",cc:"mq",tz:"America/Martinique",region:"americas",pop:0},
  {name:"Le Lamentin",country:"Martinique",cc:"mq",tz:"America/Martinique",region:"americas",pop:0},
  {name:"Le Robert",country:"Martinique",cc:"mq",tz:"America/Martinique",region:"americas",pop:0},
  {name:"Sainte-Marie",country:"Martinique",cc:"mq",tz:"America/Martinique",region:"americas",pop:0},
  {name:"Gros Islet",country:"Saint Lucia",cc:"lc",tz:"America/St_Lucia",region:"americas",pop:0},
  {name:"Castries",country:"Saint Lucia",cc:"lc",tz:"America/St_Lucia",region:"americas",pop:0},
  {name:"Gustavia",country:"Saint Barthelemy",cc:"bl",tz:"America/St_Barthelemy",region:"americas",pop:0},
  {name:"Halifax",country:"Canada",cc:"ca",tz:"America/Halifax",region:"americas",pop:1},
  {name:"Sydney",country:"Canada",cc:"ca",tz:"America/Halifax",region:"americas",pop:1},
  {name:"Dartmouth",country:"Canada",cc:"ca",tz:"America/Halifax",region:"americas",pop:0},
  {name:"Moncton",country:"Canada",cc:"ca",tz:"America/Halifax",region:"americas",pop:0},
  {name:"Hamilton",country:"Bermuda",cc:"bm",tz:"Atlantic/Bermuda",region:"americas",pop:0},
  {name:"Kingstown",country:"Saint Vincent and the Grenadines",cc:"vc",tz:"America/St_Vincent",region:"americas",pop:0},
  {name:"Calliaqua",country:"Saint Vincent and the Grenadines",cc:"vc",tz:"America/St_Vincent",region:"americas",pop:0},
  {name:"Kralendijk",country:"Bonaire, Saint Eustatius and Saba ",cc:"bq",tz:"America/Kralendijk",region:"americas",pop:0},
  {name:"Les Abymes",country:"Guadeloupe",cc:"gp",tz:"America/Guadeloupe",region:"americas",pop:0},
  {name:"Baie-Mahault",country:"Guadeloupe",cc:"gp",tz:"America/Guadeloupe",region:"americas",pop:0},
  {name:"Le Gosier",country:"Guadeloupe",cc:"gp",tz:"America/Guadeloupe",region:"americas",pop:0},
  {name:"Petit-Bourg",country:"Guadeloupe",cc:"gp",tz:"America/Guadeloupe",region:"americas",pop:0},
  {name:"Marigot",country:"Saint Martin",cc:"mf",tz:"America/Marigot",region:"americas",pop:0},
  {name:"Oranjestad",country:"Aruba",cc:"aw",tz:"America/Aruba",region:"americas",pop:0},
  {name:"Noord",country:"Aruba",cc:"aw",tz:"America/Aruba",region:"americas",pop:0},
  {name:"Tanki Leendert",country:"Aruba",cc:"aw",tz:"America/Aruba",region:"americas",pop:0},
  {name:"San Nicolas",country:"Aruba",cc:"aw",tz:"America/Aruba",region:"americas",pop:0},
  {name:"Philipsburg",country:"Sint Maarten",cc:"sx",tz:"America/Lower_Princes",region:"americas",pop:0},
  {name:"Road Town",country:"British Virgin Islands",cc:"vg",tz:"America/Tortola",region:"americas",pop:0},
  {name:"Roseau",country:"Dominica",cc:"dm",tz:"America/Dominica",region:"americas",pop:0},
  {name:"Saint Croix",country:"U.S. Virgin Islands",cc:"vi",tz:"America/St_Thomas",region:"americas",pop:0},
  {name:"Charlotte Amalie",country:"U.S. Virgin Islands",cc:"vi",tz:"America/St_Thomas",region:"americas",pop:0},
  {name:"Saint George's",country:"Grenada",cc:"gd",tz:"America/Grenada",region:"americas",pop:0},
  {name:"Saint John\u2019s",country:"Antigua and Barbuda",cc:"ag",tz:"America/Antigua",region:"americas",pop:0},
  {name:"San Juan",country:"Puerto Rico",cc:"pr",tz:"America/Puerto_Rico",region:"americas",pop:1},
  {name:"Bayam\u00f3n",country:"Puerto Rico",cc:"pr",tz:"America/Puerto_Rico",region:"americas",pop:0},
  {name:"Carolina",country:"Puerto Rico",cc:"pr",tz:"America/Puerto_Rico",region:"americas",pop:0},
  {name:"Ponce",country:"Puerto Rico",cc:"pr",tz:"America/Puerto_Rico",region:"americas",pop:0},
  {name:"Santo Domingo",country:"Dominican Republic",cc:"do",tz:"America/Santo_Domingo",region:"americas",pop:1},
  {name:"Santiago de los Caballeros",country:"Dominican Republic",cc:"do",tz:"America/Santo_Domingo",region:"americas",pop:0},
  {name:"Santo Domingo Oeste",country:"Dominican Republic",cc:"do",tz:"America/Santo_Domingo",region:"americas",pop:0},
  {name:"Santo Domingo Este",country:"Dominican Republic",cc:"do",tz:"America/Santo_Domingo",region:"americas",pop:0},
  {name:"The Valley",country:"Anguilla",cc:"ai",tz:"America/Anguilla",region:"americas",pop:0},
  {name:"Thule",country:"Greenland",cc:"gl",tz:"America/Thule",region:"americas",pop:0},
  {name:"Willemstad",country:"Curacao",cc:"cw",tz:"America/Curacao",region:"americas",pop:0},
  {name:"Bandariba",country:"Curacao",cc:"cw",tz:"America/Curacao",region:"americas",pop:0},
  {name:"La Paz",country:"Bolivia",cc:"bo",tz:"America/La_Paz",region:"americas",pop:1},
  {name:"Santa Cruz de la Sierra",country:"Bolivia",cc:"bo",tz:"America/La_Paz",region:"americas",pop:0},
  {name:"Cochabamba",country:"Bolivia",cc:"bo",tz:"America/La_Paz",region:"americas",pop:0},
  {name:"Sucre",country:"Bolivia",cc:"bo",tz:"America/La_Paz",region:"americas",pop:0},
  {name:"Santiago",country:"Chile",cc:"cl",tz:"America/Santiago",region:"americas",pop:1},
  {name:"Puente Alto",country:"Chile",cc:"cl",tz:"America/Santiago",region:"americas",pop:0},
  {name:"Maip\u00fa",country:"Chile",cc:"cl",tz:"America/Santiago",region:"americas",pop:0},
  {name:"Antofagasta",country:"Chile",cc:"cl",tz:"America/Santiago",region:"americas",pop:0},
  {name:"Georgetown",country:"Guyana",cc:"gy",tz:"America/Guyana",region:"americas",pop:0},
  {name:"Linden",country:"Guyana",cc:"gy",tz:"America/Guyana",region:"americas",pop:0},
  {name:"New Amsterdam",country:"Guyana",cc:"gy",tz:"America/Guyana",region:"americas",pop:0},
  {name:"Caracas",country:"Venezuela",cc:"ve",tz:"America/Caracas",region:"americas",pop:1},
  {name:"Maracaibo",country:"Venezuela",cc:"ve",tz:"America/Caracas",region:"americas",pop:0},
  {name:"Valencia",country:"Venezuela",cc:"ve",tz:"America/Caracas",region:"americas",pop:0},
  {name:"Barquisimeto",country:"Venezuela",cc:"ve",tz:"America/Caracas",region:"americas",pop:0},
  {name:"St. John's",country:"Canada",cc:"ca",tz:"America/St_Johns",region:"americas",pop:0},
  {name:"Mount Pearl",country:"Canada",cc:"ca",tz:"America/St_Johns",region:"americas",pop:0},
  {name:"Paradise",country:"Canada",cc:"ca",tz:"America/St_Johns",region:"americas",pop:0},
  {name:"Corner Brook",country:"Canada",cc:"ca",tz:"America/St_Johns",region:"americas",pop:0},
  {name:"Buenos Aires",country:"Argentina",cc:"ar",tz:"America/Argentina/Buenos_Aires",region:"americas",pop:1},
  {name:"C\u00f3rdoba",country:"Argentina",cc:"ar",tz:"America/Argentina/Buenos_Aires",region:"americas",pop:0},
  {name:"Rosario",country:"Argentina",cc:"ar",tz:"America/Argentina/Buenos_Aires",region:"americas",pop:0},
  {name:"Mar del Plata",country:"Argentina",cc:"ar",tz:"America/Argentina/Buenos_Aires",region:"americas",pop:0},
  {name:"S\u00e3o Paulo",country:"Brazil",cc:"br",tz:"America/Sao_Paulo",region:"americas",pop:1},
  {name:"Rio de Janeiro",country:"Brazil",cc:"br",tz:"America/Sao_Paulo",region:"americas",pop:1},
  {name:"Belo Horizonte",country:"Brazil",cc:"br",tz:"America/Sao_Paulo",region:"americas",pop:0},
  {name:"Salvador",country:"Brazil",cc:"br",tz:"America/Sao_Paulo",region:"americas",pop:0},
  {name:"Palmer",country:"Antarctica",cc:"aq",tz:"Antarctica/Palmer",region:"other",pop:0},
  {name:"Rothera",country:"Antarctica",cc:"aq",tz:"Antarctica/Palmer",region:"other",pop:0},
  {name:"Punta Arenas",country:"Chile",cc:"cl",tz:"America/Punta_Arenas",region:"americas",pop:0},
  {name:"Coyhaique",country:"Chile",cc:"cl",tz:"America/Punta_Arenas",region:"americas",pop:0},
  {name:"Puerto Natales",country:"Chile",cc:"cl",tz:"America/Punta_Arenas",region:"americas",pop:0},
  {name:"Puerto Ays\u00e9n",country:"Chile",cc:"cl",tz:"America/Punta_Arenas",region:"americas",pop:0},
  {name:"Stanley",country:"Falkland Islands",cc:"fk",tz:"Atlantic/Stanley",region:"americas",pop:0},
  {name:"Cayenne",country:"French Guiana",cc:"gf",tz:"America/Cayenne",region:"americas",pop:0},
  {name:"Matoury",country:"French Guiana",cc:"gf",tz:"America/Cayenne",region:"americas",pop:0},
  {name:"Saint-Laurent-du-Maroni",country:"French Guiana",cc:"gf",tz:"America/Cayenne",region:"americas",pop:0},
  {name:"Kourou",country:"French Guiana",cc:"gf",tz:"America/Cayenne",region:"americas",pop:0},
  {name:"Asunci\u00f3n",country:"Paraguay",cc:"py",tz:"America/Asuncion",region:"americas",pop:0},
  {name:"Ciudad del Este",country:"Paraguay",cc:"py",tz:"America/Asuncion",region:"americas",pop:0},
  {name:"San Lorenzo",country:"Paraguay",cc:"py",tz:"America/Asuncion",region:"americas",pop:0},
  {name:"Capiat\u00e1",country:"Paraguay",cc:"py",tz:"America/Asuncion",region:"americas",pop:0},
  {name:"Saint-Pierre",country:"Saint Pierre and Miquelon",cc:"pm",tz:"America/Miquelon",region:"americas",pop:0},
  {name:"Paramaribo",country:"Suriname",cc:"sr",tz:"America/Paramaribo",region:"americas",pop:0},
  {name:"Blauwgrond",country:"Suriname",cc:"sr",tz:"America/Paramaribo",region:"americas",pop:0},
  {name:"Rainville",country:"Suriname",cc:"sr",tz:"America/Paramaribo",region:"americas",pop:0},
  {name:"Flora",country:"Suriname",cc:"sr",tz:"America/Paramaribo",region:"americas",pop:0},
  {name:"Montevideo",country:"Uruguay",cc:"uy",tz:"America/Montevideo",region:"americas",pop:1},
  {name:"Salto",country:"Uruguay",cc:"uy",tz:"America/Montevideo",region:"americas",pop:0},
  {name:"Paysand\u00fa",country:"Uruguay",cc:"uy",tz:"America/Montevideo",region:"americas",pop:0},
  {name:"Las Piedras",country:"Uruguay",cc:"uy",tz:"America/Montevideo",region:"americas",pop:0},
  {name:"Noronha",country:"Brazil",cc:"br",tz:"America/Noronha",region:"americas",pop:0},
  {name:"Nuuk",country:"Greenland",cc:"gl",tz:"America/Nuuk",region:"americas",pop:0},
  {name:"Scoresbysund",country:"Greenland",cc:"gl",tz:"America/Nuuk",region:"americas",pop:0},
  {name:"Grytviken",country:"South Georgia and the South Sandwich Islands",cc:"gs",tz:"Atlantic/South_Georgia",region:"other",pop:0},
  {name:"Ponta Delgada",country:"Portugal",cc:"pt",tz:"Atlantic/Azores",region:"europe",pop:0},
  {name:"Praia",country:"Cabo Verde",cc:"cv",tz:"Atlantic/Cape_Verde",region:"africa",pop:0},
  {name:"Mindelo",country:"Cabo Verde",cc:"cv",tz:"Atlantic/Cape_Verde",region:"africa",pop:0},
  {name:"Espargos",country:"Cabo Verde",cc:"cv",tz:"Atlantic/Cape_Verde",region:"africa",pop:0},
  {name:"Assomada",country:"Cabo Verde",cc:"cv",tz:"Atlantic/Cape_Verde",region:"africa",pop:0},
  {name:"Abidjan",country:"Ivory Coast",cc:"ci",tz:"Africa/Abidjan",region:"africa",pop:0},
  {name:"Abobo",country:"Ivory Coast",cc:"ci",tz:"Africa/Abidjan",region:"africa",pop:0},
  {name:"Bouak\u00e9",country:"Ivory Coast",cc:"ci",tz:"Africa/Abidjan",region:"africa",pop:0},
  {name:"Korhogo",country:"Ivory Coast",cc:"ci",tz:"Africa/Abidjan",region:"africa",pop:0},
  {name:"Bamako",country:"Mali",cc:"ml",tz:"Africa/Bamako",region:"africa",pop:0},
  {name:"Sikasso",country:"Mali",cc:"ml",tz:"Africa/Bamako",region:"africa",pop:0},
  {name:"Koutiala",country:"Mali",cc:"ml",tz:"Africa/Bamako",region:"africa",pop:0},
  {name:"S\u00e9gou",country:"Mali",cc:"ml",tz:"Africa/Bamako",region:"africa",pop:0},
  {name:"Bissau",country:"Guinea-Bissau",cc:"gw",tz:"Africa/Bissau",region:"africa",pop:0},
  {name:"Gab\u00fa",country:"Guinea-Bissau",cc:"gw",tz:"Africa/Bissau",region:"africa",pop:0},
  {name:"Bafat\u00e1",country:"Guinea-Bissau",cc:"gw",tz:"Africa/Bissau",region:"africa",pop:0},
  {name:"Xitole",country:"Guinea-Bissau",cc:"gw",tz:"Africa/Bissau",region:"africa",pop:0},
  {name:"Conakry",country:"Guinea",cc:"gn",tz:"Africa/Conakry",region:"africa",pop:0},
  {name:"Camayenne",country:"Guinea",cc:"gn",tz:"Africa/Conakry",region:"africa",pop:0},
  {name:"Nz\u00e9r\u00e9kor\u00e9",country:"Guinea",cc:"gn",tz:"Africa/Conakry",region:"africa",pop:0},
  {name:"Kankan",country:"Guinea",cc:"gn",tz:"Africa/Conakry",region:"africa",pop:0},
  {name:"Dakar",country:"Senegal",cc:"sn",tz:"Africa/Dakar",region:"africa",pop:1},
  {name:"Touba",country:"Senegal",cc:"sn",tz:"Africa/Dakar",region:"africa",pop:0},
  {name:"Pikine",country:"Senegal",cc:"sn",tz:"Africa/Dakar",region:"africa",pop:0},
  {name:"Gu\u00e9diawaye",country:"Senegal",cc:"sn",tz:"Africa/Dakar",region:"africa",pop:0},
  {name:"Danmarkshavn",country:"Greenland",cc:"gl",tz:"America/Danmarkshavn",region:"americas",pop:0},
  {name:"Douglas",country:"Isle of Man",cc:"im",tz:"Europe/Isle_of_Man",region:"europe",pop:0},
  {name:"Dublin",country:"Ireland",cc:"ie",tz:"Europe/Dublin",region:"europe",pop:1},
  {name:"South Dublin",country:"Ireland",cc:"ie",tz:"Europe/Dublin",region:"europe",pop:0},
  {name:"Cork",country:"Ireland",cc:"ie",tz:"Europe/Dublin",region:"europe",pop:0},
  {name:"Limerick",country:"Ireland",cc:"ie",tz:"Europe/Dublin",region:"europe",pop:0},
  {name:"Freetown",country:"Sierra Leone",cc:"sl",tz:"Africa/Freetown",region:"africa",pop:0},
  {name:"Bo",country:"Sierra Leone",cc:"sl",tz:"Africa/Freetown",region:"africa",pop:0},
  {name:"Kenema",country:"Sierra Leone",cc:"sl",tz:"Africa/Freetown",region:"africa",pop:0},
  {name:"Koidu",country:"Sierra Leone",cc:"sl",tz:"Africa/Freetown",region:"africa",pop:0},
  {name:"Jamestown",country:"Saint Helena",cc:"sh",tz:"Atlantic/St_Helena",region:"africa",pop:0},
  {name:"Kumasi",country:"Ghana",cc:"gh",tz:"Africa/Accra",region:"africa",pop:0},
  {name:"Accra",country:"Ghana",cc:"gh",tz:"Africa/Accra",region:"africa",pop:1},
  {name:"Tamale",country:"Ghana",cc:"gh",tz:"Africa/Accra",region:"africa",pop:0},
  {name:"Takoradi",country:"Ghana",cc:"gh",tz:"Africa/Accra",region:"africa",pop:0},
  {name:"Lom\u00e9",country:"Togo",cc:"tg",tz:"Africa/Lome",region:"africa",pop:0},
  {name:"Sokod\u00e9",country:"Togo",cc:"tg",tz:"Africa/Lome",region:"africa",pop:0},
  {name:"Kara",country:"Togo",cc:"tg",tz:"Africa/Lome",region:"africa",pop:0},
  {name:"Atakpam\u00e9",country:"Togo",cc:"tg",tz:"Africa/Lome",region:"africa",pop:0},
  {name:"London",country:"United Kingdom",cc:"gb",tz:"Europe/London",region:"europe",pop:1},
  {name:"Birmingham",country:"United Kingdom",cc:"gb",tz:"Europe/London",region:"europe",pop:0},
  {name:"Glasgow",country:"United Kingdom",cc:"gb",tz:"Europe/London",region:"europe",pop:0},
  {name:"Manchester",country:"United Kingdom",cc:"gb",tz:"Europe/London",region:"europe",pop:0},
  {name:"Monrovia",country:"Liberia",cc:"lr",tz:"Africa/Monrovia",region:"africa",pop:0},
  {name:"Gbarnga",country:"Liberia",cc:"lr",tz:"Africa/Monrovia",region:"africa",pop:0},
  {name:"Buchanan",country:"Liberia",cc:"lr",tz:"Africa/Monrovia",region:"africa",pop:0},
  {name:"Ganta",country:"Liberia",cc:"lr",tz:"Africa/Monrovia",region:"africa",pop:0},
  {name:"Nouakchott",country:"Mauritania",cc:"mr",tz:"Africa/Nouakchott",region:"africa",pop:0},
  {name:"Nouadhibou",country:"Mauritania",cc:"mr",tz:"Africa/Nouakchott",region:"africa",pop:0},
  {name:"Kiffa",country:"Mauritania",cc:"mr",tz:"Africa/Nouakchott",region:"africa",pop:0},
  {name:"Dar Naim",country:"Mauritania",cc:"mr",tz:"Africa/Nouakchott",region:"africa",pop:0},
  {name:"Ouagadougou",country:"Burkina Faso",cc:"bf",tz:"Africa/Ouagadougou",region:"africa",pop:0},
  {name:"Bobo-Dioulasso",country:"Burkina Faso",cc:"bf",tz:"Africa/Ouagadougou",region:"africa",pop:0},
  {name:"Koudougou",country:"Burkina Faso",cc:"bf",tz:"Africa/Ouagadougou",region:"africa",pop:0},
  {name:"Saaba",country:"Burkina Faso",cc:"bf",tz:"Africa/Ouagadougou",region:"africa",pop:0},
  {name:"Reykjav\u00edk",country:"Iceland",cc:"is",tz:"Atlantic/Reykjavik",region:"europe",pop:0},
  {name:"K\u00f3pavogur",country:"Iceland",cc:"is",tz:"Atlantic/Reykjavik",region:"europe",pop:0},
  {name:"Hafnarfj\u00f6r\u00f0ur",country:"Iceland",cc:"is",tz:"Atlantic/Reykjavik",region:"europe",pop:0},
  {name:"Reykjanesb\u00e6r",country:"Iceland",cc:"is",tz:"Atlantic/Reykjavik",region:"europe",pop:0},
  {name:"Saint Helier",country:"Jersey",cc:"je",tz:"Europe/Jersey",region:"europe",pop:0},
  {name:"Saint Peter Port",country:"Guernsey",cc:"gg",tz:"Europe/Guernsey",region:"europe",pop:0},
  {name:"Serekunda",country:"Gambia",cc:"gm",tz:"Africa/Banjul",region:"africa",pop:0},
  {name:"Brikama",country:"Gambia",cc:"gm",tz:"Africa/Banjul",region:"africa",pop:0},
  {name:"Bununka Kunda",country:"Gambia",cc:"gm",tz:"Africa/Banjul",region:"africa",pop:0},
  {name:"Sukuta",country:"Gambia",cc:"gm",tz:"Africa/Banjul",region:"africa",pop:0},
  {name:"S\u00e3o Tom\u00e9",country:"Sao Tome and Principe",cc:"st",tz:"Africa/Sao_Tome",region:"africa",pop:0},
  {name:"Troll",country:"Antarctica",cc:"aq",tz:"Antarctica/Troll",region:"other",pop:0},
  {name:"Casablanca",country:"Morocco",cc:"ma",tz:"Africa/Casablanca",region:"africa",pop:1},
  {name:"Rabat",country:"Morocco",cc:"ma",tz:"Africa/Casablanca",region:"africa",pop:0},
  {name:"Fes",country:"Morocco",cc:"ma",tz:"Africa/Casablanca",region:"africa",pop:0},
  {name:"Tangier",country:"Morocco",cc:"ma",tz:"Africa/Casablanca",region:"africa",pop:0},
  {name:"Laayoune",country:"Western Sahara",cc:"eh",tz:"Africa/El_Aaiun",region:"africa",pop:0},
  {name:"Dakhla",country:"Western Sahara",cc:"eh",tz:"Africa/El_Aaiun",region:"africa",pop:0},
  {name:"Boujdour",country:"Western Sahara",cc:"eh",tz:"Africa/El_Aaiun",region:"africa",pop:0},
  {name:"Las Palmas de Gran Canaria",country:"Spain",cc:"es",tz:"Atlantic/Canary",region:"europe",pop:0},
  {name:"Santa Cruz de Tenerife",country:"Spain",cc:"es",tz:"Atlantic/Canary",region:"europe",pop:0},
  {name:"La Laguna",country:"Spain",cc:"es",tz:"Atlantic/Canary",region:"europe",pop:0},
  {name:"Telde",country:"Spain",cc:"es",tz:"Atlantic/Canary",region:"europe",pop:0},
  {name:"Lisbon",country:"Portugal",cc:"pt",tz:"Europe/Lisbon",region:"europe",pop:1},
  {name:"Porto",country:"Portugal",cc:"pt",tz:"Europe/Lisbon",region:"europe",pop:0},
  {name:"Amadora",country:"Portugal",cc:"pt",tz:"Europe/Lisbon",region:"europe",pop:0},
  {name:"Braga",country:"Portugal",cc:"pt",tz:"Europe/Lisbon",region:"europe",pop:0},
  {name:"T\u00f3rshavn",country:"Faroe Islands",cc:"fo",tz:"Atlantic/Faroe",region:"europe",pop:0},
  {name:"Windhoek",country:"Namibia",cc:"na",tz:"Africa/Windhoek",region:"africa",pop:0},
  {name:"Rundu",country:"Namibia",cc:"na",tz:"Africa/Windhoek",region:"africa",pop:0},
  {name:"Walvis Bay",country:"Namibia",cc:"na",tz:"Africa/Windhoek",region:"africa",pop:0},
  {name:"Swakopmund",country:"Namibia",cc:"na",tz:"Africa/Windhoek",region:"africa",pop:0},
  {name:"Algiers",country:"Algeria",cc:"dz",tz:"Africa/Algiers",region:"africa",pop:1},
  {name:"Oran",country:"Algeria",cc:"dz",tz:"Africa/Algiers",region:"africa",pop:0},
  {name:"Constantine",country:"Algeria",cc:"dz",tz:"Africa/Algiers",region:"africa",pop:0},
  {name:"Annaba",country:"Algeria",cc:"dz",tz:"Africa/Algiers",region:"africa",pop:0},
  {name:"Andorra la Vella",country:"Andorra",cc:"ad",tz:"Europe/Andorra",region:"europe",pop:0},
  {name:"les Escaldes",country:"Andorra",cc:"ad",tz:"Europe/Andorra",region:"europe",pop:0},
  {name:"Belgrade",country:"Serbia",cc:"rs",tz:"Europe/Belgrade",region:"europe",pop:1},
  {name:"Ni\u0161",country:"Serbia",cc:"rs",tz:"Europe/Belgrade",region:"europe",pop:0},
  {name:"Novi Sad",country:"Serbia",cc:"rs",tz:"Europe/Belgrade",region:"europe",pop:0},
  {name:"Zemun",country:"Serbia",cc:"rs",tz:"Europe/Belgrade",region:"europe",pop:0},
  {name:"Berlin",country:"Germany",cc:"de",tz:"Europe/Berlin",region:"europe",pop:1},
  {name:"Hamburg",country:"Germany",cc:"de",tz:"Europe/Berlin",region:"europe",pop:0},
  {name:"Munich",country:"Germany",cc:"de",tz:"Europe/Berlin",region:"europe",pop:1},
  {name:"K\u00f6ln",country:"Germany",cc:"de",tz:"Europe/Berlin",region:"europe",pop:0},
  {name:"Bratislava",country:"Slovakia",cc:"sk",tz:"Europe/Bratislava",region:"europe",pop:0},
  {name:"Ko\u0161ice",country:"Slovakia",cc:"sk",tz:"Europe/Bratislava",region:"europe",pop:0},
  {name:"Petr\u017ealka",country:"Slovakia",cc:"sk",tz:"Europe/Bratislava",region:"europe",pop:0},
  {name:"Nitra",country:"Slovakia",cc:"sk",tz:"Europe/Bratislava",region:"europe",pop:0},
  {name:"Brussels",country:"Belgium",cc:"be",tz:"Europe/Brussels",region:"europe",pop:1},
  {name:"Antwerpen",country:"Belgium",cc:"be",tz:"Europe/Brussels",region:"europe",pop:0},
  {name:"Gent",country:"Belgium",cc:"be",tz:"Europe/Brussels",region:"europe",pop:0},
  {name:"Charleroi",country:"Belgium",cc:"be",tz:"Europe/Brussels",region:"europe",pop:0},
  {name:"Budapest",country:"Hungary",cc:"hu",tz:"Europe/Budapest",region:"europe",pop:1},
  {name:"Debrecen",country:"Hungary",cc:"hu",tz:"Europe/Budapest",region:"europe",pop:0},
  {name:"Szeged",country:"Hungary",cc:"hu",tz:"Europe/Budapest",region:"europe",pop:0},
  {name:"Miskolc",country:"Hungary",cc:"hu",tz:"Europe/Budapest",region:"europe",pop:0},
  {name:"Copenhagen",country:"Denmark",cc:"dk",tz:"Europe/Copenhagen",region:"europe",pop:1},
  {name:"\u00c5rhus",country:"Denmark",cc:"dk",tz:"Europe/Copenhagen",region:"europe",pop:0},
  {name:"Odense",country:"Denmark",cc:"dk",tz:"Europe/Copenhagen",region:"europe",pop:0},
  {name:"Aalborg",country:"Denmark",cc:"dk",tz:"Europe/Copenhagen",region:"europe",pop:0},
  {name:"Gibraltar",country:"Gibraltar",cc:"gi",tz:"Europe/Gibraltar",region:"europe",pop:0},
  {name:"Ljubljana",country:"Slovenia",cc:"si",tz:"Europe/Ljubljana",region:"europe",pop:0},
  {name:"Maribor",country:"Slovenia",cc:"si",tz:"Europe/Ljubljana",region:"europe",pop:0},
  {name:"Celje",country:"Slovenia",cc:"si",tz:"Europe/Ljubljana",region:"europe",pop:0},
  {name:"Kranj",country:"Slovenia",cc:"si",tz:"Europe/Ljubljana",region:"europe",pop:0},
  {name:"Longyearbyen",country:"Svalbard and Jan Mayen",cc:"sj",tz:"Arctic/Longyearbyen",region:"europe",pop:0},
  {name:"Luxembourg",country:"Luxembourg",cc:"lu",tz:"Europe/Luxembourg",region:"europe",pop:0},
  {name:"Esch-sur-Alzette",country:"Luxembourg",cc:"lu",tz:"Europe/Luxembourg",region:"europe",pop:0},
  {name:"Dudelange",country:"Luxembourg",cc:"lu",tz:"Europe/Luxembourg",region:"europe",pop:0},
  {name:"Madrid",country:"Spain",cc:"es",tz:"Europe/Madrid",region:"europe",pop:1},
  {name:"Barcelona",country:"Spain",cc:"es",tz:"Europe/Madrid",region:"europe",pop:0},
  {name:"Zaragoza",country:"Spain",cc:"es",tz:"Europe/Madrid",region:"europe",pop:0},
  {name:"Monaco",country:"Monaco",cc:"mc",tz:"Europe/Monaco",region:"europe",pop:0},
  {name:"Monte-Carlo",country:"Monaco",cc:"mc",tz:"Europe/Monaco",region:"europe",pop:0},
  {name:"Oslo",country:"Norway",cc:"no",tz:"Europe/Oslo",region:"europe",pop:1},
  {name:"Bergen",country:"Norway",cc:"no",tz:"Europe/Oslo",region:"europe",pop:0},
  {name:"Trondheim",country:"Norway",cc:"no",tz:"Europe/Oslo",region:"europe",pop:0},
  {name:"Stavanger",country:"Norway",cc:"no",tz:"Europe/Oslo",region:"europe",pop:0},
  {name:"Paris",country:"France",cc:"fr",tz:"Europe/Paris",region:"europe",pop:1},
  {name:"Marseille",country:"France",cc:"fr",tz:"Europe/Paris",region:"europe",pop:0},
  {name:"Lyon",country:"France",cc:"fr",tz:"Europe/Paris",region:"europe",pop:0},
  {name:"Toulouse",country:"France",cc:"fr",tz:"Europe/Paris",region:"europe",pop:0},
  {name:"Podgorica",country:"Montenegro",cc:"me",tz:"Europe/Podgorica",region:"europe",pop:0},
  {name:"Nik\u0161i\u0107",country:"Montenegro",cc:"me",tz:"Europe/Podgorica",region:"europe",pop:0},
  {name:"Herceg Novi",country:"Montenegro",cc:"me",tz:"Europe/Podgorica",region:"europe",pop:0},
  {name:"Pljevlja",country:"Montenegro",cc:"me",tz:"Europe/Podgorica",region:"europe",pop:0},
  {name:"Prague",country:"Czechia",cc:"cz",tz:"Europe/Prague",region:"europe",pop:1},
  {name:"Brno",country:"Czechia",cc:"cz",tz:"Europe/Prague",region:"europe",pop:0},
  {name:"Ostrava",country:"Czechia",cc:"cz",tz:"Europe/Prague",region:"europe",pop:0},
  {name:"Pilsen",country:"Czechia",cc:"cz",tz:"Europe/Prague",region:"europe",pop:0},
  {name:"Rome",country:"Italy",cc:"it",tz:"Europe/Rome",region:"europe",pop:1},
  {name:"Milan",country:"Italy",cc:"it",tz:"Europe/Rome",region:"europe",pop:0},
  {name:"Naples",country:"Italy",cc:"it",tz:"Europe/Rome",region:"europe",pop:0},
  {name:"Turin",country:"Italy",cc:"it",tz:"Europe/Rome",region:"europe",pop:0},
  {name:"Rotterdam",country:"The Netherlands",cc:"nl",tz:"Europe/Amsterdam",region:"europe",pop:0},
  {name:"Amsterdam",country:"The Netherlands",cc:"nl",tz:"Europe/Amsterdam",region:"europe",pop:1},
  {name:"The Hague",country:"The Netherlands",cc:"nl",tz:"Europe/Amsterdam",region:"europe",pop:0},
  {name:"Utrecht",country:"The Netherlands",cc:"nl",tz:"Europe/Amsterdam",region:"europe",pop:0},
  {name:"San Marino",country:"San Marino",cc:"sm",tz:"Europe/San_Marino",region:"europe",pop:0},
  {name:"San Pawl il-Ba\u0127ar",country:"Malta",cc:"mt",tz:"Europe/Malta",region:"europe",pop:0},
  {name:"Birkirkara",country:"Malta",cc:"mt",tz:"Europe/Malta",region:"europe",pop:0},
  {name:"Mosta",country:"Malta",cc:"mt",tz:"Europe/Malta",region:"europe",pop:0},
  {name:"Sliema",country:"Malta",cc:"mt",tz:"Europe/Malta",region:"europe",pop:0},
  {name:"Sarajevo",country:"Bosnia and Herzegovina",cc:"ba",tz:"Europe/Sarajevo",region:"europe",pop:0},
  {name:"Banja Luka",country:"Bosnia and Herzegovina",cc:"ba",tz:"Europe/Sarajevo",region:"europe",pop:0},
  {name:"Zenica",country:"Bosnia and Herzegovina",cc:"ba",tz:"Europe/Sarajevo",region:"europe",pop:0},
  {name:"Tuzla",country:"Bosnia and Herzegovina",cc:"ba",tz:"Europe/Sarajevo",region:"europe",pop:0},
  {name:"Skopje",country:"North Macedonia",cc:"mk",tz:"Europe/Skopje",region:"europe",pop:0},
  {name:"Kumanovo",country:"North Macedonia",cc:"mk",tz:"Europe/Skopje",region:"europe",pop:0},
  {name:"Prilep",country:"North Macedonia",cc:"mk",tz:"Europe/Skopje",region:"europe",pop:0},
  {name:"Bitola",country:"North Macedonia",cc:"mk",tz:"Europe/Skopje",region:"europe",pop:0},
  {name:"Stockholm",country:"Sweden",cc:"se",tz:"Europe/Stockholm",region:"europe",pop:1},
  {name:"G\u00f6teborg",country:"Sweden",cc:"se",tz:"Europe/Stockholm",region:"europe",pop:0},
  {name:"Malm\u00f6",country:"Sweden",cc:"se",tz:"Europe/Stockholm",region:"europe",pop:0},
  {name:"Uppsala",country:"Sweden",cc:"se",tz:"Europe/Stockholm",region:"europe",pop:0},
  {name:"Tirana",country:"Albania",cc:"al",tz:"Europe/Tirane",region:"europe",pop:0},
  {name:"Durr\u00ebs",country:"Albania",cc:"al",tz:"Europe/Tirane",region:"europe",pop:0},
  {name:"Vlor\u00eb",country:"Albania",cc:"al",tz:"Europe/Tirane",region:"europe",pop:0},
  {name:"Elbasan",country:"Albania",cc:"al",tz:"Europe/Tirane",region:"europe",pop:0},
  {name:"Tunis",country:"Tunisia",cc:"tn",tz:"Africa/Tunis",region:"africa",pop:1},
  {name:"Sfax",country:"Tunisia",cc:"tn",tz:"Africa/Tunis",region:"africa",pop:0},
  {name:"Sousse",country:"Tunisia",cc:"tn",tz:"Africa/Tunis",region:"africa",pop:0},
  {name:"Kairouan",country:"Tunisia",cc:"tn",tz:"Africa/Tunis",region:"africa",pop:0},
  {name:"Vaduz",country:"Liechtenstein",cc:"li",tz:"Europe/Vaduz",region:"europe",pop:0},
  {name:"Vatican City",country:"Vatican",cc:"va",tz:"Europe/Vatican",region:"europe",pop:0},
  {name:"Vienna",country:"Austria",cc:"at",tz:"Europe/Vienna",region:"europe",pop:1},
  {name:"Graz",country:"Austria",cc:"at",tz:"Europe/Vienna",region:"europe",pop:0},
  {name:"Linz",country:"Austria",cc:"at",tz:"Europe/Vienna",region:"europe",pop:0},
  {name:"Favoriten",country:"Austria",cc:"at",tz:"Europe/Vienna",region:"europe",pop:0},
  {name:"Warsaw",country:"Poland",cc:"pl",tz:"Europe/Warsaw",region:"europe",pop:1},
  {name:"\u0141\u00f3d\u017a",country:"Poland",cc:"pl",tz:"Europe/Warsaw",region:"europe",pop:0},
  {name:"Krak\u00f3w",country:"Poland",cc:"pl",tz:"Europe/Warsaw",region:"europe",pop:0},
  {name:"Wroc\u0142aw",country:"Poland",cc:"pl",tz:"Europe/Warsaw",region:"europe",pop:0},
  {name:"Zagreb",country:"Croatia",cc:"hr",tz:"Europe/Zagreb",region:"europe",pop:0},
  {name:"Split",country:"Croatia",cc:"hr",tz:"Europe/Zagreb",region:"europe",pop:0},
  {name:"Rijeka",country:"Croatia",cc:"hr",tz:"Europe/Zagreb",region:"europe",pop:0},
  {name:"Osijek",country:"Croatia",cc:"hr",tz:"Europe/Zagreb",region:"europe",pop:0},
  {name:"Z\u00fcrich",country:"Switzerland",cc:"ch",tz:"Europe/Zurich",region:"europe",pop:0},
  {name:"Gen\u00e8ve",country:"Switzerland",cc:"ch",tz:"Europe/Zurich",region:"europe",pop:0},
  {name:"Basel",country:"Switzerland",cc:"ch",tz:"Europe/Zurich",region:"europe",pop:0},
  {name:"Lausanne",country:"Switzerland",cc:"ch",tz:"Europe/Zurich",region:"europe",pop:0},
  {name:"Bangui",country:"Central African Republic",cc:"cf",tz:"Africa/Bangui",region:"africa",pop:0},
  {name:"Bimbo",country:"Central African Republic",cc:"cf",tz:"Africa/Bangui",region:"africa",pop:0},
  {name:"B\u00e9goua",country:"Central African Republic",cc:"cf",tz:"Africa/Bangui",region:"africa",pop:0},
  {name:"Carnot",country:"Central African Republic",cc:"cf",tz:"Africa/Bangui",region:"africa",pop:0},
  {name:"Bata",country:"Equatorial Guinea",cc:"gq",tz:"Africa/Malabo",region:"africa",pop:0},
  {name:"Malabo",country:"Equatorial Guinea",cc:"gq",tz:"Africa/Malabo",region:"africa",pop:0},
  {name:"Ebebiyin",country:"Equatorial Guinea",cc:"gq",tz:"Africa/Malabo",region:"africa",pop:0},
  {name:"Brazzaville",country:"Republic of the Congo",cc:"cg",tz:"Africa/Brazzaville",region:"africa",pop:0},
  {name:"Pointe-Noire",country:"Republic of the Congo",cc:"cg",tz:"Africa/Brazzaville",region:"africa",pop:0},
  {name:"Dolisie",country:"Republic of the Congo",cc:"cg",tz:"Africa/Brazzaville",region:"africa",pop:0},
  {name:"Nkayi",country:"Republic of the Congo",cc:"cg",tz:"Africa/Brazzaville",region:"africa",pop:0},
  {name:"Cotonou",country:"Benin",cc:"bj",tz:"Africa/Porto-Novo",region:"africa",pop:0},
  {name:"Abomey-Calavi",country:"Benin",cc:"bj",tz:"Africa/Porto-Novo",region:"africa",pop:0},
  {name:"Porto-Novo",country:"Benin",cc:"bj",tz:"Africa/Porto-Novo",region:"africa",pop:0},
  {name:"Parakou",country:"Benin",cc:"bj",tz:"Africa/Porto-Novo",region:"africa",pop:0},
  {name:"Douala",country:"Cameroon",cc:"cm",tz:"Africa/Douala",region:"africa",pop:0},
  {name:"Yaound\u00e9",country:"Cameroon",cc:"cm",tz:"Africa/Douala",region:"africa",pop:0},
  {name:"Bamenda",country:"Cameroon",cc:"cm",tz:"Africa/Douala",region:"africa",pop:0},
  {name:"Bafoussam",country:"Cameroon",cc:"cm",tz:"Africa/Douala",region:"africa",pop:0},
  {name:"Kinshasa",country:"Democratic Republic of the Congo",cc:"cd",tz:"Africa/Kinshasa",region:"africa",pop:1},
  {name:"Kikwit",country:"Democratic Republic of the Congo",cc:"cd",tz:"Africa/Kinshasa",region:"africa",pop:0},
  {name:"Masina",country:"Democratic Republic of the Congo",cc:"cd",tz:"Africa/Kinshasa",region:"africa",pop:0},
  {name:"Mbandaka",country:"Democratic Republic of the Congo",cc:"cd",tz:"Africa/Kinshasa",region:"africa",pop:0},
  {name:"Lagos",country:"Nigeria",cc:"ng",tz:"Africa/Lagos",region:"africa",pop:1},
  {name:"Kano",country:"Nigeria",cc:"ng",tz:"Africa/Lagos",region:"africa",pop:0},
  {name:"Ibadan",country:"Nigeria",cc:"ng",tz:"Africa/Lagos",region:"africa",pop:0},
  {name:"Abuja",country:"Nigeria",cc:"ng",tz:"Africa/Lagos",region:"africa",pop:0},
  {name:"Libreville",country:"Gabon",cc:"ga",tz:"Africa/Libreville",region:"africa",pop:0},
  {name:"Port-Gentil",country:"Gabon",cc:"ga",tz:"Africa/Libreville",region:"africa",pop:0},
  {name:"Franceville",country:"Gabon",cc:"ga",tz:"Africa/Libreville",region:"africa",pop:0},
  {name:"Owendo",country:"Gabon",cc:"ga",tz:"Africa/Libreville",region:"africa",pop:0},
  {name:"Luanda",country:"Angola",cc:"ao",tz:"Africa/Luanda",region:"africa",pop:1},
  {name:"Lubango",country:"Angola",cc:"ao",tz:"Africa/Luanda",region:"africa",pop:0},
  {name:"Huambo",country:"Angola",cc:"ao",tz:"Africa/Luanda",region:"africa",pop:0},
  {name:"Benguela",country:"Angola",cc:"ao",tz:"Africa/Luanda",region:"africa",pop:0},
  {name:"N'Djamena",country:"Chad",cc:"td",tz:"Africa/Ndjamena",region:"africa",pop:0},
  {name:"Moundou",country:"Chad",cc:"td",tz:"Africa/Ndjamena",region:"africa",pop:0},
  {name:"Ab\u00e9ch\u00e9",country:"Chad",cc:"td",tz:"Africa/Ndjamena",region:"africa",pop:0},
  {name:"Sarh",country:"Chad",cc:"td",tz:"Africa/Ndjamena",region:"africa",pop:0},
  {name:"Niamey",country:"Niger",cc:"ne",tz:"Africa/Niamey",region:"africa",pop:0},
  {name:"Maradi",country:"Niger",cc:"ne",tz:"Africa/Niamey",region:"africa",pop:0},
  {name:"Zinder",country:"Niger",cc:"ne",tz:"Africa/Niamey",region:"africa",pop:0},
  {name:"Tahoua",country:"Niger",cc:"ne",tz:"Africa/Niamey",region:"africa",pop:0},
  {name:"Bujumbura",country:"Burundi",cc:"bi",tz:"Africa/Bujumbura",region:"africa",pop:0},
  {name:"Gitega",country:"Burundi",cc:"bi",tz:"Africa/Bujumbura",region:"africa",pop:0},
  {name:"Ngozi",country:"Burundi",cc:"bi",tz:"Africa/Bujumbura",region:"africa",pop:0},
  {name:"Rumonge",country:"Burundi",cc:"bi",tz:"Africa/Bujumbura",region:"africa",pop:0},
  {name:"Gaborone",country:"Botswana",cc:"bw",tz:"Africa/Gaborone",region:"africa",pop:0},
  {name:"Francistown",country:"Botswana",cc:"bw",tz:"Africa/Gaborone",region:"africa",pop:0},
  {name:"Mogoditshane",country:"Botswana",cc:"bw",tz:"Africa/Gaborone",region:"africa",pop:0},
  {name:"Maun",country:"Botswana",cc:"bw",tz:"Africa/Gaborone",region:"africa",pop:0},
  {name:"Harare",country:"Zimbabwe",cc:"zw",tz:"Africa/Harare",region:"africa",pop:0},
  {name:"Bulawayo",country:"Zimbabwe",cc:"zw",tz:"Africa/Harare",region:"africa",pop:0},
  {name:"Chitungwiza",country:"Zimbabwe",cc:"zw",tz:"Africa/Harare",region:"africa",pop:0},
  {name:"Mutare",country:"Zimbabwe",cc:"zw",tz:"Africa/Harare",region:"africa",pop:0},
  {name:"Juba",country:"South Sudan",cc:"ss",tz:"Africa/Juba",region:"africa",pop:0},
  {name:"Winejok",country:"South Sudan",cc:"ss",tz:"Africa/Juba",region:"africa",pop:0},
  {name:"Yei",country:"South Sudan",cc:"ss",tz:"Africa/Juba",region:"africa",pop:0},
  {name:"Malakal",country:"South Sudan",cc:"ss",tz:"Africa/Juba",region:"africa",pop:0},
  {name:"Khartoum",country:"Sudan",cc:"sd",tz:"Africa/Khartoum",region:"africa",pop:1},
  {name:"Omdurman",country:"Sudan",cc:"sd",tz:"Africa/Khartoum",region:"africa",pop:0},
  {name:"Khartoum North",country:"Sudan",cc:"sd",tz:"Africa/Khartoum",region:"africa",pop:0},
  {name:"Nyala",country:"Sudan",cc:"sd",tz:"Africa/Khartoum",region:"africa",pop:0},
  {name:"Kigali",country:"Rwanda",cc:"rw",tz:"Africa/Kigali",region:"africa",pop:0},
  {name:"Gisenyi",country:"Rwanda",cc:"rw",tz:"Africa/Kigali",region:"africa",pop:0},
  {name:"Musanze",country:"Rwanda",cc:"rw",tz:"Africa/Kigali",region:"africa",pop:0},
  {name:"Nyagatare",country:"Rwanda",cc:"rw",tz:"Africa/Kigali",region:"africa",pop:0},
  {name:"Lilongwe",country:"Malawi",cc:"mw",tz:"Africa/Blantyre",region:"africa",pop:0},
  {name:"Blantyre",country:"Malawi",cc:"mw",tz:"Africa/Blantyre",region:"africa",pop:0},
  {name:"Mzuzu",country:"Malawi",cc:"mw",tz:"Africa/Blantyre",region:"africa",pop:0},
  {name:"Zomba",country:"Malawi",cc:"mw",tz:"Africa/Blantyre",region:"africa",pop:0},
  {name:"Lubumbashi",country:"Democratic Republic of the Congo",cc:"cd",tz:"Africa/Lubumbashi",region:"africa",pop:0},
  {name:"Mbuji-Mayi",country:"Democratic Republic of the Congo",cc:"cd",tz:"Africa/Lubumbashi",region:"africa",pop:0},
  {name:"Kananga",country:"Democratic Republic of the Congo",cc:"cd",tz:"Africa/Lubumbashi",region:"africa",pop:0},
  {name:"Kisangani",country:"Democratic Republic of the Congo",cc:"cd",tz:"Africa/Lubumbashi",region:"africa",pop:0},
  {name:"Lusaka",country:"Zambia",cc:"zm",tz:"Africa/Lusaka",region:"africa",pop:0},
  {name:"Kitwe",country:"Zambia",cc:"zm",tz:"Africa/Lusaka",region:"africa",pop:0},
  {name:"Ndola",country:"Zambia",cc:"zm",tz:"Africa/Lusaka",region:"africa",pop:0},
  {name:"Chipata",country:"Zambia",cc:"zm",tz:"Africa/Lusaka",region:"africa",pop:0},
  {name:"Maputo",country:"Mozambique",cc:"mz",tz:"Africa/Maputo",region:"africa",pop:0},
  {name:"Matola",country:"Mozambique",cc:"mz",tz:"Africa/Maputo",region:"africa",pop:0},
  {name:"Nampula",country:"Mozambique",cc:"mz",tz:"Africa/Maputo",region:"africa",pop:0},
  {name:"Beira",country:"Mozambique",cc:"mz",tz:"Africa/Maputo",region:"africa",pop:0},
  {name:"Athens",country:"Greece",cc:"gr",tz:"Europe/Athens",region:"europe",pop:1},
  {name:"Thessalon\u00edki",country:"Greece",cc:"gr",tz:"Europe/Athens",region:"europe",pop:0},
  {name:"P\u00e1tra",country:"Greece",cc:"gr",tz:"Europe/Athens",region:"europe",pop:0},
  {name:"Piraeus",country:"Greece",cc:"gr",tz:"Europe/Athens",region:"europe",pop:0},
  {name:"Beirut",country:"Lebanon",cc:"lb",tz:"Asia/Beirut",region:"asia",pop:1},
  {name:"Ra\u2019s Bayr\u016bt",country:"Lebanon",cc:"lb",tz:"Asia/Beirut",region:"asia",pop:0},
  {name:"Tripoli",country:"Lebanon",cc:"lb",tz:"Asia/Beirut",region:"asia",pop:0},
  {name:"Sidon",country:"Lebanon",cc:"lb",tz:"Asia/Beirut",region:"asia",pop:0},
  {name:"Bucharest",country:"Romania",cc:"ro",tz:"Europe/Bucharest",region:"europe",pop:1},
  {name:"Sector 3",country:"Romania",cc:"ro",tz:"Europe/Bucharest",region:"europe",pop:0},
  {name:"Ia\u015fi",country:"Romania",cc:"ro",tz:"Europe/Bucharest",region:"europe",pop:0},
  {name:"Sector 6",country:"Romania",cc:"ro",tz:"Europe/Bucharest",region:"europe",pop:0},
  {name:"Cairo",country:"Egypt",cc:"eg",tz:"Africa/Cairo",region:"africa",pop:1},
  {name:"Alexandria",country:"Egypt",cc:"eg",tz:"Africa/Cairo",region:"africa",pop:0},
  {name:"Giza",country:"Egypt",cc:"eg",tz:"Africa/Cairo",region:"africa",pop:0},
  {name:"Shubr\u0101 al Khaymah",country:"Egypt",cc:"eg",tz:"Africa/Cairo",region:"africa",pop:0},
  {name:"Chisinau",country:"Moldova",cc:"md",tz:"Europe/Chisinau",region:"europe",pop:0},
  {name:"Tiraspol",country:"Moldova",cc:"md",tz:"Europe/Chisinau",region:"europe",pop:0},
  {name:"B\u0103l\u0163i",country:"Moldova",cc:"md",tz:"Europe/Chisinau",region:"europe",pop:0},
  {name:"Bender",country:"Moldova",cc:"md",tz:"Europe/Chisinau",region:"europe",pop:0},
  {name:"East Jerusalem",country:"Palestinian Territory",cc:"ps",tz:"Asia/Hebron",region:"asia",pop:0},
  {name:"Gaza",country:"Palestinian Territory",cc:"ps",tz:"Asia/Hebron",region:"asia",pop:0},
  {name:"Kh\u0101n Y\u016bnis",country:"Palestinian Territory",cc:"ps",tz:"Asia/Hebron",region:"asia",pop:0},
  {name:"Jab\u0101ly\u0101",country:"Palestinian Territory",cc:"ps",tz:"Asia/Hebron",region:"asia",pop:0},
  {name:"Helsinki",country:"Finland",cc:"fi",tz:"Europe/Helsinki",region:"europe",pop:1},
  {name:"Espoo",country:"Finland",cc:"fi",tz:"Europe/Helsinki",region:"europe",pop:0},
  {name:"Tampere",country:"Finland",cc:"fi",tz:"Europe/Helsinki",region:"europe",pop:0},
  {name:"Vantaa",country:"Finland",cc:"fi",tz:"Europe/Helsinki",region:"europe",pop:0},
  {name:"Kaliningrad",country:"Russia",cc:"ru",tz:"Europe/Kaliningrad",region:"europe",pop:0},
  {name:"Chernyakhovsk",country:"Russia",cc:"ru",tz:"Europe/Kaliningrad",region:"europe",pop:0},
  {name:"Sovetsk",country:"Russia",cc:"ru",tz:"Europe/Kaliningrad",region:"europe",pop:0},
  {name:"Baltiysk",country:"Russia",cc:"ru",tz:"Europe/Kaliningrad",region:"europe",pop:0},
  {name:"Kyiv",country:"Ukraine",cc:"ua",tz:"Europe/Kyiv",region:"europe",pop:1},
  {name:"Kharkiv",country:"Ukraine",cc:"ua",tz:"Europe/Kyiv",region:"europe",pop:0},
  {name:"Odesa",country:"Ukraine",cc:"ua",tz:"Europe/Kyiv",region:"europe",pop:0},
  {name:"Dnipro",country:"Ukraine",cc:"ua",tz:"Europe/Kyiv",region:"europe",pop:0},
  {name:"Mariehamn",country:"Aland Islands",cc:"ax",tz:"Europe/Mariehamn",region:"europe",pop:0},
  {name:"Nicosia",country:"Cyprus",cc:"cy",tz:"Asia/Nicosia",region:"europe",pop:0},
  {name:"Limassol",country:"Cyprus",cc:"cy",tz:"Asia/Nicosia",region:"europe",pop:0},
  {name:"Larnaca",country:"Cyprus",cc:"cy",tz:"Asia/Nicosia",region:"europe",pop:0},
  {name:"Str\u00f3volos",country:"Cyprus",cc:"cy",tz:"Asia/Nicosia",region:"europe",pop:0},
  {name:"Riga",country:"Latvia",cc:"lv",tz:"Europe/Riga",region:"europe",pop:1},
  {name:"Daugavpils",country:"Latvia",cc:"lv",tz:"Europe/Riga",region:"europe",pop:0},
  {name:"Liep\u0101ja",country:"Latvia",cc:"lv",tz:"Europe/Riga",region:"europe",pop:0},
  {name:"Jelgava",country:"Latvia",cc:"lv",tz:"Europe/Riga",region:"europe",pop:0},
  {name:"Sofia",country:"Bulgaria",cc:"bg",tz:"Europe/Sofia",region:"europe",pop:1},
  {name:"Plovdiv",country:"Bulgaria",cc:"bg",tz:"Europe/Sofia",region:"europe",pop:0},
  {name:"Varna",country:"Bulgaria",cc:"bg",tz:"Europe/Sofia",region:"europe",pop:0},
  {name:"Burgas",country:"Bulgaria",cc:"bg",tz:"Europe/Sofia",region:"europe",pop:0},
  {name:"Tallinn",country:"Estonia",cc:"ee",tz:"Europe/Tallinn",region:"europe",pop:1},
  {name:"Tartu",country:"Estonia",cc:"ee",tz:"Europe/Tallinn",region:"europe",pop:0},
  {name:"Narva",country:"Estonia",cc:"ee",tz:"Europe/Tallinn",region:"europe",pop:0},
  {name:"P\u00e4rnu",country:"Estonia",cc:"ee",tz:"Europe/Tallinn",region:"europe",pop:0},
  {name:"Benghazi",country:"Libya",cc:"ly",tz:"Africa/Tripoli",region:"africa",pop:0},
  {name:"Misratah",country:"Libya",cc:"ly",tz:"Africa/Tripoli",region:"africa",pop:0},
  {name:"Zliten",country:"Libya",cc:"ly",tz:"Africa/Tripoli",region:"africa",pop:0},
  {name:"Vilnius",country:"Lithuania",cc:"lt",tz:"Europe/Vilnius",region:"europe",pop:0},
  {name:"Kaunas",country:"Lithuania",cc:"lt",tz:"Europe/Vilnius",region:"europe",pop:0},
  {name:"Klaip\u0117da",country:"Lithuania",cc:"lt",tz:"Europe/Vilnius",region:"europe",pop:0},
  {name:"\u0160iauliai",country:"Lithuania",cc:"lt",tz:"Europe/Vilnius",region:"europe",pop:0},
  {name:"Jerusalem",country:"Israel",cc:"il",tz:"Asia/Jerusalem",region:"asia",pop:0},
  {name:"Tel Aviv",country:"Israel",cc:"il",tz:"Asia/Jerusalem",region:"asia",pop:0},
  {name:"West Jerusalem",country:"Israel",cc:"il",tz:"Asia/Jerusalem",region:"asia",pop:0},
  {name:"Haifa",country:"Israel",cc:"il",tz:"Asia/Jerusalem",region:"asia",pop:0},
  {name:"Johannesburg",country:"South Africa",cc:"za",tz:"Africa/Johannesburg",region:"africa",pop:1},
  {name:"Cape Town",country:"South Africa",cc:"za",tz:"Africa/Johannesburg",region:"africa",pop:1},
  {name:"Durban",country:"South Africa",cc:"za",tz:"Africa/Johannesburg",region:"africa",pop:0},
  {name:"Pretoria",country:"South Africa",cc:"za",tz:"Africa/Johannesburg",region:"africa",pop:0},
  {name:"Manzini",country:"Eswatini",cc:"sz",tz:"Africa/Mbabane",region:"africa",pop:0},
  {name:"Mbabane",country:"Eswatini",cc:"sz",tz:"Africa/Mbabane",region:"africa",pop:0},
  {name:"Lobamba",country:"Eswatini",cc:"sz",tz:"Africa/Mbabane",region:"africa",pop:0},
  {name:"Maseru",country:"Lesotho",cc:"ls",tz:"Africa/Maseru",region:"africa",pop:0},
  {name:"Maputsoe",country:"Lesotho",cc:"ls",tz:"Africa/Maseru",region:"africa",pop:0},
  {name:"Mohale's Hoek",country:"Lesotho",cc:"ls",tz:"Africa/Maseru",region:"africa",pop:0},
  {name:"Mafeteng",country:"Lesotho",cc:"ls",tz:"Africa/Maseru",region:"africa",pop:0},
  {name:"Al A\u1e29mad\u012b",country:"Kuwait",cc:"kw",tz:"Asia/Kuwait",region:"asia",pop:0},
  {name:"\u1e28awall\u012b",country:"Kuwait",cc:"kw",tz:"Asia/Kuwait",region:"asia",pop:0},
  {name:"As S\u0101lim\u012byah",country:"Kuwait",cc:"kw",tz:"Asia/Kuwait",region:"asia",pop:0},
  {name:"\u015eab\u0101\u1e29 as S\u0101lim",country:"Kuwait",cc:"kw",tz:"Asia/Kuwait",region:"asia",pop:0},
  {name:"Al Muharraq",country:"Bahrain",cc:"bh",tz:"Asia/Bahrain",region:"asia",pop:0},
  {name:"Manama",country:"Bahrain",cc:"bh",tz:"Asia/Bahrain",region:"asia",pop:0},
  {name:"Mad\u012bnat \u1e28amad",country:"Bahrain",cc:"bh",tz:"Asia/Bahrain",region:"asia",pop:0},
  {name:"Ar Rif\u0101\u2018",country:"Bahrain",cc:"bh",tz:"Asia/Bahrain",region:"asia",pop:0},
  {name:"Baghdad",country:"Iraq",cc:"iq",tz:"Asia/Baghdad",region:"asia",pop:1},
  {name:"Al Maw\u015fil al Jad\u012bdah",country:"Iraq",cc:"iq",tz:"Asia/Baghdad",region:"asia",pop:0},
  {name:"Al Ba\u015frah al Qad\u012bmah",country:"Iraq",cc:"iq",tz:"Asia/Baghdad",region:"asia",pop:0},
  {name:"Mosul",country:"Iraq",cc:"iq",tz:"Asia/Baghdad",region:"asia",pop:0},
  {name:"Doha",country:"Qatar",cc:"qa",tz:"Asia/Qatar",region:"asia",pop:1},
  {name:"Ar Rayy\u0101n",country:"Qatar",cc:"qa",tz:"Asia/Qatar",region:"asia",pop:0},
  {name:"Al Ma\u0163\u0101r al \u2018At\u012bq",country:"Qatar",cc:"qa",tz:"Asia/Qatar",region:"asia",pop:0},
  {name:"Al Man\u015f\u016brah",country:"Qatar",cc:"qa",tz:"Asia/Qatar",region:"asia",pop:0},
  {name:"Jeddah",country:"Saudi Arabia",cc:"sa",tz:"Asia/Riyadh",region:"asia",pop:0},
  {name:"Riyadh",country:"Saudi Arabia",cc:"sa",tz:"Asia/Riyadh",region:"asia",pop:1},
  {name:"Makkah",country:"Saudi Arabia",cc:"sa",tz:"Asia/Riyadh",region:"asia",pop:0},
  {name:"Madinah",country:"Saudi Arabia",cc:"sa",tz:"Asia/Riyadh",region:"asia",pop:0},
  {name:"Sanaa",country:"Yemen",cc:"ye",tz:"Asia/Aden",region:"asia",pop:0},
  {name:"Aden",country:"Yemen",cc:"ye",tz:"Asia/Aden",region:"asia",pop:0},
  {name:"Taiz",country:"Yemen",cc:"ye",tz:"Asia/Aden",region:"asia",pop:0},
  {name:"Ibb",country:"Yemen",cc:"ye",tz:"Asia/Aden",region:"asia",pop:0},
  {name:"Amman",country:"Jordan",cc:"jo",tz:"Asia/Amman",region:"asia",pop:1},
  {name:"Zarqa",country:"Jordan",cc:"jo",tz:"Asia/Amman",region:"asia",pop:0},
  {name:"Irbid",country:"Jordan",cc:"jo",tz:"Asia/Amman",region:"asia",pop:0},
  {name:"Russeifa",country:"Jordan",cc:"jo",tz:"Asia/Amman",region:"asia",pop:0},
  {name:"Aleppo",country:"Syria",cc:"sy",tz:"Asia/Damascus",region:"asia",pop:0},
  {name:"Damascus",country:"Syria",cc:"sy",tz:"Asia/Damascus",region:"asia",pop:0},
  {name:"Homs",country:"Syria",cc:"sy",tz:"Asia/Damascus",region:"asia",pop:0},
  {name:"Latakia",country:"Syria",cc:"sy",tz:"Asia/Damascus",region:"asia",pop:0},
  {name:"Addis Ababa",country:"Ethiopia",cc:"et",tz:"Africa/Addis_Ababa",region:"africa",pop:1},
  {name:"Jijiga",country:"Ethiopia",cc:"et",tz:"Africa/Addis_Ababa",region:"africa",pop:0},
  {name:"Gonder",country:"Ethiopia",cc:"et",tz:"Africa/Addis_Ababa",region:"africa",pop:0},
  {name:"Mek'ele",country:"Ethiopia",cc:"et",tz:"Africa/Addis_Ababa",region:"africa",pop:0},
  {name:"Antananarivo",country:"Madagascar",cc:"mg",tz:"Indian/Antananarivo",region:"africa",pop:0},
  {name:"Toamasina",country:"Madagascar",cc:"mg",tz:"Indian/Antananarivo",region:"africa",pop:0},
  {name:"Antsirabe",country:"Madagascar",cc:"mg",tz:"Indian/Antananarivo",region:"africa",pop:0},
  {name:"Mahajanga",country:"Madagascar",cc:"mg",tz:"Indian/Antananarivo",region:"africa",pop:0},
  {name:"Asmara",country:"Eritrea",cc:"er",tz:"Africa/Asmara",region:"africa",pop:0},
  {name:"Keren",country:"Eritrea",cc:"er",tz:"Africa/Asmara",region:"africa",pop:0},
  {name:"Himora",country:"Eritrea",cc:"er",tz:"Africa/Asmara",region:"africa",pop:0},
  {name:"Massawa",country:"Eritrea",cc:"er",tz:"Africa/Asmara",region:"africa",pop:0},
  {name:"Dar es Salaam",country:"Tanzania",cc:"tz",tz:"Africa/Dar_es_Salaam",region:"africa",pop:0},
  {name:"Mwanza",country:"Tanzania",cc:"tz",tz:"Africa/Dar_es_Salaam",region:"africa",pop:0},
  {name:"Dodoma",country:"Tanzania",cc:"tz",tz:"Africa/Dar_es_Salaam",region:"africa",pop:0},
  {name:"Zanzibar",country:"Tanzania",cc:"tz",tz:"Africa/Dar_es_Salaam",region:"africa",pop:0},
  {name:"Djibouti",country:"Djibouti",cc:"dj",tz:"Africa/Djibouti",region:"africa",pop:0},
  {name:"Ali Sabih",country:"Djibouti",cc:"dj",tz:"Africa/Djibouti",region:"africa",pop:0},
  {name:"Dikhil",country:"Djibouti",cc:"dj",tz:"Africa/Djibouti",region:"africa",pop:0},
  {name:"Tadjoura",country:"Djibouti",cc:"dj",tz:"Africa/Djibouti",region:"africa",pop:0},
  {name:"Kampala",country:"Uganda",cc:"ug",tz:"Africa/Kampala",region:"africa",pop:0},
  {name:"Nansana",country:"Uganda",cc:"ug",tz:"Africa/Kampala",region:"africa",pop:0},
  {name:"Kira",country:"Uganda",cc:"ug",tz:"Africa/Kampala",region:"africa",pop:0},
  {name:"Bunamwaya",country:"Uganda",cc:"ug",tz:"Africa/Kampala",region:"africa",pop:0},
  {name:"Mamoudzou",country:"Mayotte",cc:"yt",tz:"Indian/Mayotte",region:"africa",pop:0},
  {name:"Koungou",country:"Mayotte",cc:"yt",tz:"Indian/Mayotte",region:"africa",pop:0},
  {name:"Labattoir",country:"Mayotte",cc:"yt",tz:"Indian/Mayotte",region:"africa",pop:0},
  {name:"Kaou\u00e9ni",country:"Mayotte",cc:"yt",tz:"Indian/Mayotte",region:"africa",pop:0},
  {name:"Mogadishu",country:"Somalia",cc:"so",tz:"Africa/Mogadishu",region:"africa",pop:0},
  {name:"Borama",country:"Somalia",cc:"so",tz:"Africa/Mogadishu",region:"africa",pop:0},
  {name:"Hargeysa",country:"Somalia",cc:"so",tz:"Africa/Mogadishu",region:"africa",pop:0},
  {name:"Berbera",country:"Somalia",cc:"so",tz:"Africa/Mogadishu",region:"africa",pop:0},
  {name:"Moroni",country:"Comoros",cc:"km",tz:"Indian/Comoro",region:"africa",pop:0},
  {name:"Moutsamoudou",country:"Comoros",cc:"km",tz:"Indian/Comoro",region:"africa",pop:0},
  {name:"Fomboni",country:"Comoros",cc:"km",tz:"Indian/Comoro",region:"africa",pop:0},
  {name:"Nairobi",country:"Kenya",cc:"ke",tz:"Africa/Nairobi",region:"africa",pop:1},
  {name:"Kakamega",country:"Kenya",cc:"ke",tz:"Africa/Nairobi",region:"africa",pop:0},
  {name:"Mombasa",country:"Kenya",cc:"ke",tz:"Africa/Nairobi",region:"africa",pop:0},
  {name:"Nakuru",country:"Kenya",cc:"ke",tz:"Africa/Nairobi",region:"africa",pop:0},
  {name:"Minsk",country:"Belarus",cc:"by",tz:"Europe/Minsk",region:"europe",pop:0},
  {name:"Homyel'",country:"Belarus",cc:"by",tz:"Europe/Minsk",region:"europe",pop:0},
  {name:"Hrodna",country:"Belarus",cc:"by",tz:"Europe/Minsk",region:"europe",pop:0},
  {name:"Vitebsk",country:"Belarus",cc:"by",tz:"Europe/Minsk",region:"europe",pop:0},
  {name:"Moscow",country:"Russia",cc:"ru",tz:"Europe/Moscow",region:"europe",pop:1},
  {name:"Saint Petersburg",country:"Russia",cc:"ru",tz:"Europe/Moscow",region:"europe",pop:0},
  {name:"Nizhniy Novgorod",country:"Russia",cc:"ru",tz:"Europe/Moscow",region:"europe",pop:0},
  {name:"Kazan",country:"Russia",cc:"ru",tz:"Europe/Moscow",region:"europe",pop:0},
  {name:"Sevastopol",country:"Ukraine",cc:"ua",tz:"Europe/Simferopol",region:"europe",pop:0},
  {name:"Simferopol",country:"Ukraine",cc:"ua",tz:"Europe/Simferopol",region:"europe",pop:0},
  {name:"Kerch",country:"Ukraine",cc:"ua",tz:"Europe/Simferopol",region:"europe",pop:0},
  {name:"Yevpatoriya",country:"Ukraine",cc:"ua",tz:"Europe/Simferopol",region:"europe",pop:0},
  {name:"Syowa",country:"Antarctica",cc:"aq",tz:"Antarctica/Syowa",region:"other",pop:0},
  {name:"Istanbul",country:"Turkey",cc:"tr",tz:"Europe/Istanbul",region:"asia",pop:1},
  {name:"Ankara",country:"Turkey",cc:"tr",tz:"Europe/Istanbul",region:"asia",pop:1},
  {name:"Bursa",country:"Turkey",cc:"tr",tz:"Europe/Istanbul",region:"asia",pop:0},
  {name:"\u0130zmir",country:"Turkey",cc:"tr",tz:"Europe/Istanbul",region:"asia",pop:0},
  {name:"Tehran",country:"Iran",cc:"ir",tz:"Asia/Tehran",region:"asia",pop:1},
  {name:"Mashhad",country:"Iran",cc:"ir",tz:"Asia/Tehran",region:"asia",pop:0},
  {name:"Isfahan",country:"Iran",cc:"ir",tz:"Asia/Tehran",region:"asia",pop:0},
  {name:"Karaj",country:"Iran",cc:"ir",tz:"Asia/Tehran",region:"asia",pop:0},
  {name:"Yerevan",country:"Armenia",cc:"am",tz:"Asia/Yerevan",region:"asia",pop:1},
  {name:"Malatia-Sebastia",country:"Armenia",cc:"am",tz:"Asia/Yerevan",region:"asia",pop:0},
  {name:"Shengavit",country:"Armenia",cc:"am",tz:"Asia/Yerevan",region:"asia",pop:0},
  {name:"Nor Nork",country:"Armenia",cc:"am",tz:"Asia/Yerevan",region:"asia",pop:0},
  {name:"Baku",country:"Azerbaijan",cc:"az",tz:"Asia/Baku",region:"asia",pop:1},
  {name:"Sumqay\u0131t",country:"Azerbaijan",cc:"az",tz:"Asia/Baku",region:"asia",pop:0},
  {name:"Ganja",country:"Azerbaijan",cc:"az",tz:"Asia/Baku",region:"asia",pop:0},
  {name:"Lankaran",country:"Azerbaijan",cc:"az",tz:"Asia/Baku",region:"asia",pop:0},
  {name:"Tbilisi",country:"Georgia",cc:"ge",tz:"Asia/Tbilisi",region:"asia",pop:1},
  {name:"Batumi",country:"Georgia",cc:"ge",tz:"Asia/Tbilisi",region:"asia",pop:0},
  {name:"Kutaisi",country:"Georgia",cc:"ge",tz:"Asia/Tbilisi",region:"asia",pop:0},
  {name:"Rustavi",country:"Georgia",cc:"ge",tz:"Asia/Tbilisi",region:"asia",pop:0},
  {name:"Dubai",country:"United Arab Emirates",cc:"ae",tz:"Asia/Dubai",region:"asia",pop:1},
  {name:"Abu Dhabi",country:"United Arab Emirates",cc:"ae",tz:"Asia/Dubai",region:"asia",pop:1},
  {name:"Sharjah",country:"United Arab Emirates",cc:"ae",tz:"Asia/Dubai",region:"asia",pop:0},
  {name:"Al Ain City",country:"United Arab Emirates",cc:"ae",tz:"Asia/Dubai",region:"asia",pop:0},
  {name:"Muscat",country:"Oman",cc:"om",tz:"Asia/Muscat",region:"asia",pop:1},
  {name:"Seeb",country:"Oman",cc:"om",tz:"Asia/Muscat",region:"asia",pop:0},
  {name:"Bawshar",country:"Oman",cc:"om",tz:"Asia/Muscat",region:"asia",pop:0},
  {name:"\u2018Ibr\u012b",country:"Oman",cc:"om",tz:"Asia/Muscat",region:"asia",pop:0},
  {name:"Port Louis",country:"Mauritius",cc:"mu",tz:"Indian/Mauritius",region:"africa",pop:0},
  {name:"Vacoas",country:"Mauritius",cc:"mu",tz:"Indian/Mauritius",region:"africa",pop:0},
  {name:"Beau Bassin-Rose Hill",country:"Mauritius",cc:"mu",tz:"Indian/Mauritius",region:"africa",pop:0},
  {name:"Curepipe",country:"Mauritius",cc:"mu",tz:"Indian/Mauritius",region:"africa",pop:0},
  {name:"Saint-Denis",country:"Reunion",cc:"re",tz:"Indian/Reunion",region:"africa",pop:0},
  {name:"Saint-Paul",country:"Reunion",cc:"re",tz:"Indian/Reunion",region:"africa",pop:0},
  {name:"Le Tampon",country:"Reunion",cc:"re",tz:"Indian/Reunion",region:"africa",pop:0},
  {name:"Samara",country:"Russia",cc:"ru",tz:"Europe/Samara",region:"europe",pop:0},
  {name:"Saratov",country:"Russia",cc:"ru",tz:"Europe/Samara",region:"europe",pop:0},
  {name:"Tolyatti",country:"Russia",cc:"ru",tz:"Europe/Samara",region:"europe",pop:0},
  {name:"Izhevsk",country:"Russia",cc:"ru",tz:"Europe/Samara",region:"europe",pop:0},
  {name:"Kabul",country:"Afghanistan",cc:"af",tz:"Asia/Kabul",region:"asia",pop:1},
  {name:"Her\u0101t",country:"Afghanistan",cc:"af",tz:"Asia/Kabul",region:"asia",pop:0},
  {name:"Maz\u0101r-e Shar\u012bf",country:"Afghanistan",cc:"af",tz:"Asia/Kabul",region:"asia",pop:0},
  {name:"Kandah\u0101r",country:"Afghanistan",cc:"af",tz:"Asia/Kabul",region:"asia",pop:0},
  {name:"Port-aux-Fran\u00e7ais",country:"French Southern Territories",cc:"tf",tz:"Indian/Kerguelen",region:"other",pop:0},
  {name:"Almaty",country:"Kazakhstan",cc:"kz",tz:"Asia/Almaty",region:"asia",pop:0},
  {name:"Shymkent",country:"Kazakhstan",cc:"kz",tz:"Asia/Almaty",region:"asia",pop:0},
  {name:"Aktobe",country:"Kazakhstan",cc:"kz",tz:"Asia/Almaty",region:"asia",pop:0},
  {name:"Karagandy",country:"Kazakhstan",cc:"kz",tz:"Asia/Almaty",region:"asia",pop:0},
  {name:"Male",country:"Maldives",cc:"mv",tz:"Indian/Maldives",region:"asia",pop:0},
  {name:"Mawson",country:"Antarctica",cc:"aq",tz:"Antarctica/Mawson",region:"other",pop:0},
  {name:"Vostok",country:"Antarctica",cc:"aq",tz:"Antarctica/Mawson",region:"other",pop:0},
  {name:"Lahore",country:"Pakistan",cc:"pk",tz:"Asia/Karachi",region:"asia",pop:1},
  {name:"Karachi",country:"Pakistan",cc:"pk",tz:"Asia/Karachi",region:"asia",pop:1},
  {name:"Peshawar",country:"Pakistan",cc:"pk",tz:"Asia/Karachi",region:"asia",pop:0},
  {name:"Faisalabad",country:"Pakistan",cc:"pk",tz:"Asia/Karachi",region:"asia",pop:0},
  {name:"Dushanbe",country:"Tajikistan",cc:"tj",tz:"Asia/Dushanbe",region:"asia",pop:0},
  {name:"Isfara",country:"Tajikistan",cc:"tj",tz:"Asia/Dushanbe",region:"asia",pop:0},
  {name:"Istaravshan",country:"Tajikistan",cc:"tj",tz:"Asia/Dushanbe",region:"asia",pop:0},
  {name:"K\u016dlob",country:"Tajikistan",cc:"tj",tz:"Asia/Dushanbe",region:"asia",pop:0},
  {name:"Ashgabat",country:"Turkmenistan",cc:"tm",tz:"Asia/Ashgabat",region:"asia",pop:0},
  {name:"T\u00fcrkmenabat",country:"Turkmenistan",cc:"tm",tz:"Asia/Ashgabat",region:"asia",pop:0},
  {name:"Da\u015foguz",country:"Turkmenistan",cc:"tm",tz:"Asia/Ashgabat",region:"asia",pop:0},
  {name:"Mary",country:"Turkmenistan",cc:"tm",tz:"Asia/Ashgabat",region:"asia",pop:0},
  {name:"Tashkent",country:"Uzbekistan",cc:"uz",tz:"Asia/Tashkent",region:"asia",pop:1},
  {name:"Andijon",country:"Uzbekistan",cc:"uz",tz:"Asia/Tashkent",region:"asia",pop:0},
  {name:"Namangan",country:"Uzbekistan",cc:"uz",tz:"Asia/Tashkent",region:"asia",pop:0},
  {name:"Samarkand",country:"Uzbekistan",cc:"uz",tz:"Asia/Tashkent",region:"asia",pop:0},
  {name:"Yekaterinburg",country:"Russia",cc:"ru",tz:"Asia/Yekaterinburg",region:"europe",pop:1},
  {name:"Chelyabinsk",country:"Russia",cc:"ru",tz:"Asia/Yekaterinburg",region:"europe",pop:0},
  {name:"Ufa",country:"Russia",cc:"ru",tz:"Asia/Yekaterinburg",region:"europe",pop:0},
  {name:"Perm",country:"Russia",cc:"ru",tz:"Asia/Yekaterinburg",region:"europe",pop:0},
  {name:"Colombo",country:"Sri Lanka",cc:"lk",tz:"Asia/Colombo",region:"asia",pop:1},
  {name:"Dehiwala-Mount Lavinia",country:"Sri Lanka",cc:"lk",tz:"Asia/Colombo",region:"asia",pop:0},
  {name:"Maharagama",country:"Sri Lanka",cc:"lk",tz:"Asia/Colombo",region:"asia",pop:0},
  {name:"Jaffna",country:"Sri Lanka",cc:"lk",tz:"Asia/Colombo",region:"asia",pop:0},
  {name:"Mumbai",country:"India",cc:"in",tz:"Asia/Kolkata",region:"asia",pop:1},
  {name:"Delhi",country:"India",cc:"in",tz:"Asia/Kolkata",region:"asia",pop:1},
  {name:"Bengaluru",country:"India",cc:"in",tz:"Asia/Kolkata",region:"asia",pop:1},
  {name:"Hyderabad",country:"India",cc:"in",tz:"Asia/Kolkata",region:"asia",pop:1},
  {name:"Kathmandu",country:"Nepal",cc:"np",tz:"Asia/Kathmandu",region:"asia",pop:1},
  {name:"Pokhara",country:"Nepal",cc:"np",tz:"Asia/Kathmandu",region:"asia",pop:0},
  {name:"Bharatpur",country:"Nepal",cc:"np",tz:"Asia/Kathmandu",region:"asia",pop:0},
  {name:"P\u0101tan",country:"Nepal",cc:"np",tz:"Asia/Kathmandu",region:"asia",pop:0},
  {name:"Dhaka",country:"Bangladesh",cc:"bd",tz:"Asia/Dhaka",region:"asia",pop:1},
  {name:"Chattogram",country:"Bangladesh",cc:"bd",tz:"Asia/Dhaka",region:"asia",pop:0},
  {name:"Gazipur",country:"Bangladesh",cc:"bd",tz:"Asia/Dhaka",region:"asia",pop:0},
  {name:"Khulna",country:"Bangladesh",cc:"bd",tz:"Asia/Dhaka",region:"asia",pop:0},
  {name:"Thimphu",country:"Bhutan",cc:"bt",tz:"Asia/Thimphu",region:"asia",pop:0},
  {name:"Phuntsholing",country:"Bhutan",cc:"bt",tz:"Asia/Thimphu",region:"asia",pop:0},
  {name:"Tsirang",country:"Bhutan",cc:"bt",tz:"Asia/Thimphu",region:"asia",pop:0},
  {name:"Pun\u0101kha",country:"Bhutan",cc:"bt",tz:"Asia/Thimphu",region:"asia",pop:0},
  {name:"\u00dcr\u00fcmqi",country:"China",cc:"cn",tz:"Asia/Urumqi",region:"asia",pop:0},
  {name:"Shihezi",country:"China",cc:"cn",tz:"Asia/Urumqi",region:"asia",pop:0},
  {name:"Korla",country:"China",cc:"cn",tz:"Asia/Urumqi",region:"asia",pop:0},
  {name:"Aqsu",country:"China",cc:"cn",tz:"Asia/Urumqi",region:"asia",pop:0},
  {name:"Chagos",country:"British Indian Ocean Territory",cc:"io",tz:"Indian/Chagos",region:"asia",pop:0},
  {name:"Bishkek",country:"Kyrgyzstan",cc:"kg",tz:"Asia/Bishkek",region:"asia",pop:0},
  {name:"Osh",country:"Kyrgyzstan",cc:"kg",tz:"Asia/Bishkek",region:"asia",pop:0},
  {name:"Jalal-Abad",country:"Kyrgyzstan",cc:"kg",tz:"Asia/Bishkek",region:"asia",pop:0},
  {name:"Karakol",country:"Kyrgyzstan",cc:"kg",tz:"Asia/Bishkek",region:"asia",pop:0},
  {name:"Omsk",country:"Russia",cc:"ru",tz:"Asia/Omsk",region:"europe",pop:0},
  {name:"Tara",country:"Russia",cc:"ru",tz:"Asia/Omsk",region:"europe",pop:0},
  {name:"Kalachinsk",country:"Russia",cc:"ru",tz:"Asia/Omsk",region:"europe",pop:0},
  {name:"Isil\u2019kul\u2019",country:"Russia",cc:"ru",tz:"Asia/Omsk",region:"europe",pop:0},
  {name:"West Island",country:"Cocos Islands",cc:"cc",tz:"Indian/Cocos",region:"asia",pop:0},
  {name:"Yangon",country:"Myanmar",cc:"mm",tz:"Asia/Yangon",region:"asia",pop:1},
  {name:"Mandalay",country:"Myanmar",cc:"mm",tz:"Asia/Yangon",region:"asia",pop:0},
  {name:"Nay Pyi Taw",country:"Myanmar",cc:"mm",tz:"Asia/Yangon",region:"asia",pop:0},
  {name:"Hlaingthaya Township",country:"Myanmar",cc:"mm",tz:"Asia/Yangon",region:"asia",pop:0},
  {name:"Flying Fish Cove",country:"Christmas Island",cc:"cx",tz:"Indian/Christmas",region:"oceania",pop:0},
  {name:"Davis",country:"Antarctica",cc:"aq",tz:"Antarctica/Davis",region:"other",pop:0},
  {name:"Ulaangom",country:"Mongolia",cc:"mn",tz:"Asia/Hovd",region:"asia",pop:0},
  {name:"Khovd",country:"Mongolia",cc:"mn",tz:"Asia/Hovd",region:"asia",pop:0},
  {name:"\u00d6lgii",country:"Mongolia",cc:"mn",tz:"Asia/Hovd",region:"asia",pop:0},
  {name:"Altai",country:"Mongolia",cc:"mn",tz:"Asia/Hovd",region:"asia",pop:0},
  {name:"Bangkok",country:"Thailand",cc:"th",tz:"Asia/Bangkok",region:"asia",pop:1},
  {name:"Samut Prakan",country:"Thailand",cc:"th",tz:"Asia/Bangkok",region:"asia",pop:0},
  {name:"Mueang Nonthaburi",country:"Thailand",cc:"th",tz:"Asia/Bangkok",region:"asia",pop:0},
  {name:"Chon Buri",country:"Thailand",cc:"th",tz:"Asia/Bangkok",region:"asia",pop:0},
  {name:"Ho Chi Minh City",country:"Vietnam",cc:"vn",tz:"Asia/Ho_Chi_Minh",region:"asia",pop:0},
  {name:"C\u1ea7n Th\u01a1",country:"Vietnam",cc:"vn",tz:"Asia/Ho_Chi_Minh",region:"asia",pop:0},
  {name:"Da Nang",country:"Vietnam",cc:"vn",tz:"Asia/Ho_Chi_Minh",region:"asia",pop:0},
  {name:"Bi\u00ean H\u00f2a",country:"Vietnam",cc:"vn",tz:"Asia/Ho_Chi_Minh",region:"asia",pop:0},
  {name:"Phnom Penh",country:"Cambodia",cc:"kh",tz:"Asia/Phnom_Penh",region:"asia",pop:1},
  {name:"Takeo",country:"Cambodia",cc:"kh",tz:"Asia/Phnom_Penh",region:"asia",pop:0},
  {name:"Siem Reap",country:"Cambodia",cc:"kh",tz:"Asia/Phnom_Penh",region:"asia",pop:0},
  {name:"Battambang",country:"Cambodia",cc:"kh",tz:"Asia/Phnom_Penh",region:"asia",pop:0},
  {name:"Vientiane",country:"Laos",cc:"la",tz:"Asia/Vientiane",region:"asia",pop:0},
  {name:"Savannakhet",country:"Laos",cc:"la",tz:"Asia/Vientiane",region:"asia",pop:0},
  {name:"Pakse",country:"Laos",cc:"la",tz:"Asia/Vientiane",region:"asia",pop:0},
  {name:"Thakh\u00e8k",country:"Laos",cc:"la",tz:"Asia/Vientiane",region:"asia",pop:0},
  {name:"Novosibirsk",country:"Russia",cc:"ru",tz:"Asia/Novosibirsk",region:"europe",pop:1},
  {name:"Krasnoyarsk",country:"Russia",cc:"ru",tz:"Asia/Novosibirsk",region:"europe",pop:0},
  {name:"Barnaul",country:"Russia",cc:"ru",tz:"Asia/Novosibirsk",region:"europe",pop:0},
  {name:"Tomsk",country:"Russia",cc:"ru",tz:"Asia/Novosibirsk",region:"europe",pop:0},
  {name:"Jakarta",country:"Indonesia",cc:"id",tz:"Asia/Jakarta",region:"asia",pop:1},
  {name:"Surabaya",country:"Indonesia",cc:"id",tz:"Asia/Jakarta",region:"asia",pop:0},
  {name:"Bekasi",country:"Indonesia",cc:"id",tz:"Asia/Jakarta",region:"asia",pop:0},
  {name:"Bandung",country:"Indonesia",cc:"id",tz:"Asia/Jakarta",region:"asia",pop:0},
  {name:"Casey",country:"Antarctica",cc:"aq",tz:"Antarctica/Casey",region:"other",pop:0},
  {name:"Perth",country:"Australia",cc:"au",tz:"Australia/Perth",region:"oceania",pop:1},
  {name:"Mandurah",country:"Australia",cc:"au",tz:"Australia/Perth",region:"oceania",pop:0},
  {name:"Bunbury",country:"Australia",cc:"au",tz:"Australia/Perth",region:"oceania",pop:0},
  {name:"Geraldton",country:"Australia",cc:"au",tz:"Australia/Perth",region:"oceania",pop:0},
  {name:"Bandar Seri Begawan",country:"Brunei",cc:"bn",tz:"Asia/Brunei",region:"asia",pop:0},
  {name:"Sengkurong",country:"Brunei",cc:"bn",tz:"Asia/Brunei",region:"asia",pop:0},
  {name:"Mentiri",country:"Brunei",cc:"bn",tz:"Asia/Brunei",region:"asia",pop:0},
  {name:"Kuala Belait",country:"Brunei",cc:"bn",tz:"Asia/Brunei",region:"asia",pop:0},
  {name:"Makassar",country:"Indonesia",cc:"id",tz:"Asia/Makassar",region:"asia",pop:0},
  {name:"Samarinda",country:"Indonesia",cc:"id",tz:"Asia/Makassar",region:"asia",pop:0},
  {name:"Denpasar",country:"Indonesia",cc:"id",tz:"Asia/Makassar",region:"asia",pop:0},
  {name:"Balikpapan",country:"Indonesia",cc:"id",tz:"Asia/Makassar",region:"asia",pop:0},
  {name:"Macau",country:"Macao",cc:"mo",tz:"Asia/Macau",region:"asia",pop:0},
  {name:"Taipa",country:"Macao",cc:"mo",tz:"Asia/Macau",region:"asia",pop:0},
  {name:"S\u00e9",country:"Macao",cc:"mo",tz:"Asia/Macau",region:"asia",pop:0},
  {name:"Luhuan",country:"Macao",cc:"mo",tz:"Asia/Macau",region:"asia",pop:0},
  {name:"Shanghai",country:"China",cc:"cn",tz:"Asia/Shanghai",region:"asia",pop:1},
  {name:"Beijing",country:"China",cc:"cn",tz:"Asia/Shanghai",region:"asia",pop:1},
  {name:"Shenzhen",country:"China",cc:"cn",tz:"Asia/Shanghai",region:"asia",pop:0},
  {name:"Guangzhou",country:"China",cc:"cn",tz:"Asia/Shanghai",region:"asia",pop:0},
  {name:"Hong Kong",country:"Hong Kong",cc:"hk",tz:"Asia/Hong_Kong",region:"asia",pop:1},
  {name:"New Territories",country:"Hong Kong",cc:"hk",tz:"Asia/Hong_Kong",region:"asia",pop:0},
  {name:"Kowloon",country:"Hong Kong",cc:"hk",tz:"Asia/Hong_Kong",region:"asia",pop:0},
  {name:"Hong Kong Island",country:"Hong Kong",cc:"hk",tz:"Asia/Hong_Kong",region:"asia",pop:0},
  {name:"Irkutsk",country:"Russia",cc:"ru",tz:"Asia/Irkutsk",region:"europe",pop:0},
  {name:"Ulan-Ude",country:"Russia",cc:"ru",tz:"Asia/Irkutsk",region:"europe",pop:0},
  {name:"Bratsk",country:"Russia",cc:"ru",tz:"Asia/Irkutsk",region:"europe",pop:0},
  {name:"Angarsk",country:"Russia",cc:"ru",tz:"Asia/Irkutsk",region:"europe",pop:0},
  {name:"Kuala Lumpur",country:"Malaysia",cc:"my",tz:"Asia/Kuala_Lumpur",region:"asia",pop:1},
  {name:"Johor Bahru",country:"Malaysia",cc:"my",tz:"Asia/Kuala_Lumpur",region:"asia",pop:0},
  {name:"Kampung Baru Subang",country:"Malaysia",cc:"my",tz:"Asia/Kuala_Lumpur",region:"asia",pop:0},
  {name:"Petaling Jaya",country:"Malaysia",cc:"my",tz:"Asia/Kuala_Lumpur",region:"asia",pop:0},
  {name:"Quezon City",country:"Philippines",cc:"ph",tz:"Asia/Manila",region:"asia",pop:0},
  {name:"Davao",country:"Philippines",cc:"ph",tz:"Asia/Manila",region:"asia",pop:0},
  {name:"Caloocan City",country:"Philippines",cc:"ph",tz:"Asia/Manila",region:"asia",pop:0},
  {name:"Manila",country:"Philippines",cc:"ph",tz:"Asia/Manila",region:"asia",pop:1},
  {name:"Singapore",country:"Singapore",cc:"sg",tz:"Asia/Singapore",region:"asia",pop:1},
  {name:"Ulu Bedok",country:"Singapore",cc:"sg",tz:"Asia/Singapore",region:"asia",pop:0},
  {name:"Bedok New Town",country:"Singapore",cc:"sg",tz:"Asia/Singapore",region:"asia",pop:0},
  {name:"Tampines Estate",country:"Singapore",cc:"sg",tz:"Asia/Singapore",region:"asia",pop:0},
  {name:"Taipei",country:"Taiwan",cc:"tw",tz:"Asia/Taipei",region:"asia",pop:1},
  {name:"New Taipei City",country:"Taiwan",cc:"tw",tz:"Asia/Taipei",region:"asia",pop:0},
  {name:"Taichung",country:"Taiwan",cc:"tw",tz:"Asia/Taipei",region:"asia",pop:0},
  {name:"Kaohsiung",country:"Taiwan",cc:"tw",tz:"Asia/Taipei",region:"asia",pop:0},
  {name:"Ulan Bator",country:"Mongolia",cc:"mn",tz:"Asia/Ulaanbaatar",region:"asia",pop:0},
  {name:"Erdenet",country:"Mongolia",cc:"mn",tz:"Asia/Ulaanbaatar",region:"asia",pop:0},
  {name:"Darhan",country:"Mongolia",cc:"mn",tz:"Asia/Ulaanbaatar",region:"asia",pop:0},
  {name:"Choibalsan",country:"Mongolia",cc:"mn",tz:"Asia/Ulaanbaatar",region:"asia",pop:0},
  {name:"Eucla",country:"Australia",cc:"au",tz:"Australia/Eucla",region:"oceania",pop:0},
  {name:"Jayapura",country:"Indonesia",cc:"id",tz:"Asia/Jayapura",region:"asia",pop:0},
  {name:"Ambon",country:"Indonesia",cc:"id",tz:"Asia/Jayapura",region:"asia",pop:0},
  {name:"Sorong",country:"Indonesia",cc:"id",tz:"Asia/Jayapura",region:"asia",pop:0},
  {name:"Ternate",country:"Indonesia",cc:"id",tz:"Asia/Jayapura",region:"asia",pop:0},
  {name:"Tokyo",country:"Japan",cc:"jp",tz:"Asia/Tokyo",region:"asia",pop:1},
  {name:"Yokohama",country:"Japan",cc:"jp",tz:"Asia/Tokyo",region:"asia",pop:0},
  {name:"Osaka",country:"Japan",cc:"jp",tz:"Asia/Tokyo",region:"asia",pop:0},
  {name:"Nagoya",country:"Japan",cc:"jp",tz:"Asia/Tokyo",region:"asia",pop:0},
  {name:"Pyongyang",country:"North Korea",cc:"kp",tz:"Asia/Pyongyang",region:"asia",pop:0},
  {name:"Hamh\u016dng",country:"North Korea",cc:"kp",tz:"Asia/Pyongyang",region:"asia",pop:0},
  {name:"Namp\u2019o",country:"North Korea",cc:"kp",tz:"Asia/Pyongyang",region:"asia",pop:0},
  {name:"Sunch\u2019\u014fn",country:"North Korea",cc:"kp",tz:"Asia/Pyongyang",region:"asia",pop:0},
  {name:"Seoul",country:"South Korea",cc:"kr",tz:"Asia/Seoul",region:"asia",pop:1},
  {name:"Busan",country:"South Korea",cc:"kr",tz:"Asia/Seoul",region:"asia",pop:0},
  {name:"Incheon",country:"South Korea",cc:"kr",tz:"Asia/Seoul",region:"asia",pop:0},
  {name:"Daegu",country:"South Korea",cc:"kr",tz:"Asia/Seoul",region:"asia",pop:0},
  {name:"Ngerulmud",country:"Palau",cc:"pw",tz:"Pacific/Palau",region:"oceania",pop:0},
  {name:"Dili",country:"Timor Leste",cc:"tl",tz:"Asia/Dili",region:"oceania",pop:0},
  {name:"Maliana",country:"Timor Leste",cc:"tl",tz:"Asia/Dili",region:"oceania",pop:0},
  {name:"Suai",country:"Timor Leste",cc:"tl",tz:"Asia/Dili",region:"oceania",pop:0},
  {name:"Likis\u00e1",country:"Timor Leste",cc:"tl",tz:"Asia/Dili",region:"oceania",pop:0},
  {name:"Chita",country:"Russia",cc:"ru",tz:"Asia/Chita",region:"europe",pop:0},
  {name:"Yakutsk",country:"Russia",cc:"ru",tz:"Asia/Chita",region:"europe",pop:0},
  {name:"Blagoveshchensk",country:"Russia",cc:"ru",tz:"Asia/Chita",region:"europe",pop:0},
  {name:"Belogorsk",country:"Russia",cc:"ru",tz:"Asia/Chita",region:"europe",pop:0},
  {name:"Adelaide",country:"Australia",cc:"au",tz:"Australia/Adelaide",region:"oceania",pop:1},
  {name:"Adelaide Hills",country:"Australia",cc:"au",tz:"Australia/Adelaide",region:"oceania",pop:0},
  {name:"Mount Gambier",country:"Australia",cc:"au",tz:"Australia/Adelaide",region:"oceania",pop:0},
  {name:"Morphett Vale",country:"Australia",cc:"au",tz:"Australia/Adelaide",region:"oceania",pop:0},
  {name:"Darwin",country:"Australia",cc:"au",tz:"Australia/Darwin",region:"oceania",pop:0},
  {name:"Palmerston",country:"Australia",cc:"au",tz:"Australia/Darwin",region:"oceania",pop:0},
  {name:"Alice Springs",country:"Australia",cc:"au",tz:"Australia/Darwin",region:"oceania",pop:0},
  {name:"Brisbane",country:"Australia",cc:"au",tz:"Australia/Brisbane",region:"oceania",pop:1},
  {name:"Gold Coast",country:"Australia",cc:"au",tz:"Australia/Brisbane",region:"oceania",pop:0},
  {name:"Sunshine Coast",country:"Australia",cc:"au",tz:"Australia/Brisbane",region:"oceania",pop:0},
  {name:"Logan City",country:"Australia",cc:"au",tz:"Australia/Brisbane",region:"oceania",pop:0},
  {name:"Melbourne",country:"Australia",cc:"au",tz:"Australia/Sydney",region:"oceania",pop:1},
  {name:"Newcastle",country:"Australia",cc:"au",tz:"Australia/Sydney",region:"oceania",pop:0},
  {name:"Canberra",country:"Australia",cc:"au",tz:"Australia/Sydney",region:"oceania",pop:0},
  {name:"Dededo Village",country:"Guam",cc:"gu",tz:"Pacific/Guam",region:"oceania",pop:0},
  {name:"Yigo Village",country:"Guam",cc:"gu",tz:"Pacific/Guam",region:"oceania",pop:0},
  {name:"Tamuning-Tumon-Harmon Village",country:"Guam",cc:"gu",tz:"Pacific/Guam",region:"oceania",pop:0},
  {name:"Tamuning",country:"Guam",cc:"gu",tz:"Pacific/Guam",region:"oceania",pop:0},
  {name:"Saipan",country:"Northern Mariana Islands",cc:"mp",tz:"Pacific/Saipan",region:"oceania",pop:0},
  {name:"Chuuk",country:"Micronesia",cc:"fm",tz:"Pacific/Chuuk",region:"oceania",pop:0},
  {name:"DumontDUrville",country:"Antarctica",cc:"aq",tz:"Antarctica/DumontDUrville",region:"other",pop:0},
  {name:"Port Moresby",country:"Papua New Guinea",cc:"pg",tz:"Pacific/Port_Moresby",region:"oceania",pop:1},
  {name:"Lae",country:"Papua New Guinea",cc:"pg",tz:"Pacific/Port_Moresby",region:"oceania",pop:0},
  {name:"Mount Hagen",country:"Papua New Guinea",cc:"pg",tz:"Pacific/Port_Moresby",region:"oceania",pop:0},
  {name:"Popondetta",country:"Papua New Guinea",cc:"pg",tz:"Pacific/Port_Moresby",region:"oceania",pop:0},
  {name:"Khabarovsk",country:"Russia",cc:"ru",tz:"Asia/Vladivostok",region:"europe",pop:0},
  {name:"Vladivostok",country:"Russia",cc:"ru",tz:"Asia/Vladivostok",region:"europe",pop:1},
  {name:"Khabarovsk Vtoroy",country:"Russia",cc:"ru",tz:"Asia/Vladivostok",region:"europe",pop:0},
  {name:"Komsomolsk-on-Amur",country:"Russia",cc:"ru",tz:"Asia/Vladivostok",region:"europe",pop:0},
  {name:"Lord Howe",country:"Australia",cc:"au",tz:"Australia/Lord_Howe",region:"oceania",pop:0},
  {name:"Arawa",country:"Papua New Guinea",cc:"pg",tz:"Pacific/Bougainville",region:"oceania",pop:0},
  {name:"Kosrae",country:"Micronesia",cc:"fm",tz:"Pacific/Kosrae",region:"oceania",pop:0},
  {name:"Palikir",country:"Micronesia",cc:"fm",tz:"Pacific/Kosrae",region:"oceania",pop:0},
  {name:"Noum\u00e9a",country:"New Caledonia",cc:"nc",tz:"Pacific/Noumea",region:"oceania",pop:0},
  {name:"Mont-Dore",country:"New Caledonia",cc:"nc",tz:"Pacific/Noumea",region:"oceania",pop:0},
  {name:"Dumb\u00e9a",country:"New Caledonia",cc:"nc",tz:"Pacific/Noumea",region:"oceania",pop:0},
  {name:"Yuzhno-Sakhalinsk",country:"Russia",cc:"ru",tz:"Asia/Sakhalin",region:"europe",pop:0},
  {name:"Magadan",country:"Russia",cc:"ru",tz:"Asia/Sakhalin",region:"europe",pop:0},
  {name:"Korsakov",country:"Russia",cc:"ru",tz:"Asia/Sakhalin",region:"europe",pop:0},
  {name:"Kholmsk",country:"Russia",cc:"ru",tz:"Asia/Sakhalin",region:"europe",pop:0},
  {name:"Honiara",country:"Solomon Islands",cc:"sb",tz:"Pacific/Guadalcanal",region:"oceania",pop:0},
  {name:"Panatina",country:"Solomon Islands",cc:"sb",tz:"Pacific/Guadalcanal",region:"oceania",pop:0},
  {name:"Nggosi",country:"Solomon Islands",cc:"sb",tz:"Pacific/Guadalcanal",region:"oceania",pop:0},
  {name:"Tandai",country:"Solomon Islands",cc:"sb",tz:"Pacific/Guadalcanal",region:"oceania",pop:0},
  {name:"Port-Vila",country:"Vanuatu",cc:"vu",tz:"Pacific/Efate",region:"oceania",pop:0},
  {name:"Nasinu",country:"Fiji",cc:"fj",tz:"Pacific/Fiji",region:"oceania",pop:0},
  {name:"Suva",country:"Fiji",cc:"fj",tz:"Pacific/Fiji",region:"oceania",pop:1},
  {name:"Lautoka",country:"Fiji",cc:"fj",tz:"Pacific/Fiji",region:"oceania",pop:0},
  {name:"Nadi",country:"Fiji",cc:"fj",tz:"Pacific/Fiji",region:"oceania",pop:0},
  {name:"Tarawa",country:"Kiribati",cc:"ki",tz:"Pacific/Tarawa",region:"oceania",pop:0},
  {name:"Petropavlovsk-Kamchatsky",country:"Russia",cc:"ru",tz:"Asia/Kamchatka",region:"europe",pop:0},
  {name:"Yelizovo",country:"Russia",cc:"ru",tz:"Asia/Kamchatka",region:"europe",pop:0},
  {name:"Vilyuchinsk",country:"Russia",cc:"ru",tz:"Asia/Kamchatka",region:"europe",pop:0},
  {name:"Anadyr",country:"Russia",cc:"ru",tz:"Asia/Kamchatka",region:"europe",pop:1},
  {name:"Majuro",country:"Marshall Islands",cc:"mh",tz:"Pacific/Majuro",region:"oceania",pop:0},
  {name:"Kwajalein",country:"Marshall Islands",cc:"mh",tz:"Pacific/Majuro",region:"oceania",pop:0},
  {name:"Yaren",country:"Nauru",cc:"nr",tz:"Pacific/Nauru",region:"oceania",pop:0},
  {name:"Auckland",country:"New Zealand",cc:"nz",tz:"Pacific/Auckland",region:"oceania",pop:1},
  {name:"Christchurch",country:"New Zealand",cc:"nz",tz:"Pacific/Auckland",region:"oceania",pop:0},
  {name:"Wellington",country:"New Zealand",cc:"nz",tz:"Pacific/Auckland",region:"oceania",pop:1},
  {name:"Manukau City",country:"New Zealand",cc:"nz",tz:"Pacific/Auckland",region:"oceania",pop:0},
  {name:"McMurdo",country:"Antarctica",cc:"aq",tz:"Antarctica/McMurdo",region:"other",pop:0},
  {name:"Funafuti",country:"Tuvalu",cc:"tv",tz:"Pacific/Funafuti",region:"oceania",pop:0},
  {name:"Wake",country:"United States Minor Outlying Islands",cc:"um",tz:"Pacific/Wake",region:"oceania",pop:0},
  {name:"Mata-Utu",country:"Wallis and Futuna",cc:"wf",tz:"Pacific/Wallis",region:"oceania",pop:0},
  {name:"Chatham",country:"New Zealand",cc:"nz",tz:"Pacific/Chatham",region:"oceania",pop:0},
  {name:"Kanton",country:"Kiribati",cc:"ki",tz:"Pacific/Kanton",region:"oceania",pop:0},
  {name:"Apia",country:"Samoa",cc:"ws",tz:"Pacific/Apia",region:"oceania",pop:0},
  {name:"Fakaofo",country:"Tokelau",cc:"tk",tz:"Pacific/Fakaofo",region:"oceania",pop:0},
  {name:"Nuku\u2018alofa",country:"Tonga",cc:"to",tz:"Pacific/Tongatapu",region:"oceania",pop:0},
  {name:"Kiritimati",country:"Kiribati",cc:"ki",tz:"Pacific/Kiritimati",region:"oceania",pop:0},
];